// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"time"

	"github.com/dotwaffle/beamers/ent/account"
	"github.com/dotwaffle/beamers/ent/accountsession"
	"github.com/dotwaffle/beamers/ent/auditentry"
	"github.com/dotwaffle/beamers/ent/bootstrapcredential"
	"github.com/dotwaffle/beamers/ent/commandreceipt"
	"github.com/dotwaffle/beamers/ent/draftchange"
	"github.com/dotwaffle/beamers/ent/draftchangedependency"
	"github.com/dotwaffle/beamers/ent/draftedit"
	"github.com/dotwaffle/beamers/ent/event"
	"github.com/dotwaffle/beamers/ent/eventgrant"
	"github.com/dotwaffle/beamers/ent/installation"
	"github.com/dotwaffle/beamers/ent/lane"
	"github.com/dotwaffle/beamers/ent/lanedraft"
	"github.com/dotwaffle/beamers/ent/lanepublishedversion"
	"github.com/dotwaffle/beamers/ent/location"
	"github.com/dotwaffle/beamers/ent/locationdraft"
	"github.com/dotwaffle/beamers/ent/locationpublishedversion"
	"github.com/dotwaffle/beamers/ent/migration"
	"github.com/dotwaffle/beamers/ent/passwordcredential"
	"github.com/dotwaffle/beamers/ent/rundown"
	"github.com/dotwaffle/beamers/ent/schema"
	"github.com/dotwaffle/beamers/ent/session"
	"github.com/dotwaffle/beamers/ent/sessiondraft"
	"github.com/dotwaffle/beamers/ent/sessionpublishedversion"
	"github.com/dotwaffle/beamers/ent/track"
	"github.com/dotwaffle/beamers/ent/trackdraft"
	"github.com/dotwaffle/beamers/ent/trackpublishedversion"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	account.Policy = privacy.NewPolicies(schema.Account{})
	account.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := account.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = func() func(string) error {
		validators := accountDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescNormalizedName is the schema descriptor for normalized_name field.
	accountDescNormalizedName := accountFields[1].Descriptor()
	// account.NormalizedNameValidator is a validator for the "normalized_name" field. It is called by the builders before save.
	account.NormalizedNameValidator = func() func(string) error {
		validators := accountDescNormalizedName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(normalized_name string) error {
			for _, fn := range fns {
				if err := fn(normalized_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[3].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	accountsession.Policy = privacy.NewPolicies(schema.AccountSession{})
	accountsession.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := accountsession.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	accountsessionFields := schema.AccountSession{}.Fields()
	_ = accountsessionFields
	// accountsessionDescTokenHash is the schema descriptor for token_hash field.
	accountsessionDescTokenHash := accountsessionFields[1].Descriptor()
	// accountsession.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	accountsession.TokenHashValidator = func() func(string) error {
		validators := accountsessionDescTokenHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token_hash string) error {
			for _, fn := range fns {
				if err := fn(token_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountsessionDescCreatedAt is the schema descriptor for created_at field.
	accountsessionDescCreatedAt := accountsessionFields[2].Descriptor()
	// accountsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	accountsession.DefaultCreatedAt = accountsessionDescCreatedAt.Default.(func() time.Time)
	auditentry.Policy = privacy.NewPolicies(schema.AuditEntry{})
	auditentry.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := auditentry.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	auditentryFields := schema.AuditEntry{}.Fields()
	_ = auditentryFields
	// auditentryDescCreatedAt is the schema descriptor for created_at field.
	auditentryDescCreatedAt := auditentryFields[1].Descriptor()
	// auditentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditentry.DefaultCreatedAt = auditentryDescCreatedAt.Default.(func() time.Time)
	// auditentryDescAction is the schema descriptor for action field.
	auditentryDescAction := auditentryFields[2].Descriptor()
	// auditentry.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditentry.ActionValidator = func() func(string) error {
		validators := auditentryDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditentryDescTargetType is the schema descriptor for target_type field.
	auditentryDescTargetType := auditentryFields[3].Descriptor()
	// auditentry.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	auditentry.TargetTypeValidator = func() func(string) error {
		validators := auditentryDescTargetType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(target_type string) error {
			for _, fn := range fns {
				if err := fn(target_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditentryDescTargetID is the schema descriptor for target_id field.
	auditentryDescTargetID := auditentryFields[4].Descriptor()
	// auditentry.TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	auditentry.TargetIDValidator = func() func(string) error {
		validators := auditentryDescTargetID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(target_id string) error {
			for _, fn := range fns {
				if err := fn(target_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	bootstrapcredential.Policy = privacy.NewPolicies(schema.BootstrapCredential{})
	bootstrapcredential.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := bootstrapcredential.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	bootstrapcredentialFields := schema.BootstrapCredential{}.Fields()
	_ = bootstrapcredentialFields
	// bootstrapcredentialDescTokenHash is the schema descriptor for token_hash field.
	bootstrapcredentialDescTokenHash := bootstrapcredentialFields[0].Descriptor()
	// bootstrapcredential.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	bootstrapcredential.TokenHashValidator = func() func(string) error {
		validators := bootstrapcredentialDescTokenHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token_hash string) error {
			for _, fn := range fns {
				if err := fn(token_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// bootstrapcredentialDescCreatedAt is the schema descriptor for created_at field.
	bootstrapcredentialDescCreatedAt := bootstrapcredentialFields[1].Descriptor()
	// bootstrapcredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	bootstrapcredential.DefaultCreatedAt = bootstrapcredentialDescCreatedAt.Default.(func() time.Time)
	commandreceipt.Policy = privacy.NewPolicies(schema.CommandReceipt{})
	commandreceipt.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := commandreceipt.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	commandreceiptFields := schema.CommandReceipt{}.Fields()
	_ = commandreceiptFields
	// commandreceiptDescCommandID is the schema descriptor for command_id field.
	commandreceiptDescCommandID := commandreceiptFields[1].Descriptor()
	// commandreceipt.CommandIDValidator is a validator for the "command_id" field. It is called by the builders before save.
	commandreceipt.CommandIDValidator = func() func(string) error {
		validators := commandreceiptDescCommandID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(command_id string) error {
			for _, fn := range fns {
				if err := fn(command_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commandreceiptDescPayloadHash is the schema descriptor for payload_hash field.
	commandreceiptDescPayloadHash := commandreceiptFields[2].Descriptor()
	// commandreceipt.PayloadHashValidator is a validator for the "payload_hash" field. It is called by the builders before save.
	commandreceipt.PayloadHashValidator = func() func(string) error {
		validators := commandreceiptDescPayloadHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(payload_hash string) error {
			for _, fn := range fns {
				if err := fn(payload_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commandreceiptDescAction is the schema descriptor for action field.
	commandreceiptDescAction := commandreceiptFields[3].Descriptor()
	// commandreceipt.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	commandreceipt.ActionValidator = func() func(string) error {
		validators := commandreceiptDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commandreceiptDescTargetType is the schema descriptor for target_type field.
	commandreceiptDescTargetType := commandreceiptFields[4].Descriptor()
	// commandreceipt.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	commandreceipt.TargetTypeValidator = func() func(string) error {
		validators := commandreceiptDescTargetType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(target_type string) error {
			for _, fn := range fns {
				if err := fn(target_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commandreceiptDescTargetID is the schema descriptor for target_id field.
	commandreceiptDescTargetID := commandreceiptFields[5].Descriptor()
	// commandreceipt.TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	commandreceipt.TargetIDValidator = func() func(string) error {
		validators := commandreceiptDescTargetID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(target_id string) error {
			for _, fn := range fns {
				if err := fn(target_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commandreceiptDescOutcomeJSON is the schema descriptor for outcome_json field.
	commandreceiptDescOutcomeJSON := commandreceiptFields[6].Descriptor()
	// commandreceipt.OutcomeJSONValidator is a validator for the "outcome_json" field. It is called by the builders before save.
	commandreceipt.OutcomeJSONValidator = commandreceiptDescOutcomeJSON.Validators[0].(func(string) error)
	// commandreceiptDescCreatedAt is the schema descriptor for created_at field.
	commandreceiptDescCreatedAt := commandreceiptFields[7].Descriptor()
	// commandreceipt.DefaultCreatedAt holds the default value on creation for the created_at field.
	commandreceipt.DefaultCreatedAt = commandreceiptDescCreatedAt.Default.(func() time.Time)
	draftchange.Policy = privacy.NewPolicies(schema.DraftChange{})
	draftchange.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := draftchange.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	draftchangeFields := schema.DraftChange{}.Fields()
	_ = draftchangeFields
	// draftchangeDescRevision is the schema descriptor for revision field.
	draftchangeDescRevision := draftchangeFields[2].Descriptor()
	// draftchange.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	draftchange.RevisionValidator = draftchangeDescRevision.Validators[0].(func(int) error)
	// draftchangeDescKind is the schema descriptor for kind field.
	draftchangeDescKind := draftchangeFields[3].Descriptor()
	// draftchange.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	draftchange.KindValidator = func() func(string) error {
		validators := draftchangeDescKind.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(kind string) error {
			for _, fn := range fns {
				if err := fn(kind); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// draftchangeDescTargetType is the schema descriptor for target_type field.
	draftchangeDescTargetType := draftchangeFields[4].Descriptor()
	// draftchange.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	draftchange.TargetTypeValidator = func() func(string) error {
		validators := draftchangeDescTargetType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(target_type string) error {
			for _, fn := range fns {
				if err := fn(target_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// draftchangeDescTargetID is the schema descriptor for target_id field.
	draftchangeDescTargetID := draftchangeFields[5].Descriptor()
	// draftchange.TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	draftchange.TargetIDValidator = draftchangeDescTargetID.Validators[0].(func(int) error)
	// draftchangeDescFactKey is the schema descriptor for fact_key field.
	draftchangeDescFactKey := draftchangeFields[6].Descriptor()
	// draftchange.FactKeyValidator is a validator for the "fact_key" field. It is called by the builders before save.
	draftchange.FactKeyValidator = func() func(string) error {
		validators := draftchangeDescFactKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(fact_key string) error {
			for _, fn := range fns {
				if err := fn(fact_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// draftchangeDescPayloadJSON is the schema descriptor for payload_json field.
	draftchangeDescPayloadJSON := draftchangeFields[7].Descriptor()
	// draftchange.PayloadJSONValidator is a validator for the "payload_json" field. It is called by the builders before save.
	draftchange.PayloadJSONValidator = draftchangeDescPayloadJSON.Validators[0].(func(string) error)
	// draftchangeDescCreatedAt is the schema descriptor for created_at field.
	draftchangeDescCreatedAt := draftchangeFields[10].Descriptor()
	// draftchange.DefaultCreatedAt holds the default value on creation for the created_at field.
	draftchange.DefaultCreatedAt = draftchangeDescCreatedAt.Default.(func() time.Time)
	draftchangedependency.Policy = privacy.NewPolicies(schema.DraftChangeDependency{})
	draftchangedependency.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := draftchangedependency.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	draftedit.Policy = privacy.NewPolicies(schema.DraftEdit{})
	draftedit.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := draftedit.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	drafteditFields := schema.DraftEdit{}.Fields()
	_ = drafteditFields
	// drafteditDescRevision is the schema descriptor for revision field.
	drafteditDescRevision := drafteditFields[2].Descriptor()
	// draftedit.RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	draftedit.RevisionValidator = drafteditDescRevision.Validators[0].(func(int) error)
	// drafteditDescCreatedAt is the schema descriptor for created_at field.
	drafteditDescCreatedAt := drafteditFields[3].Descriptor()
	// draftedit.DefaultCreatedAt holds the default value on creation for the created_at field.
	draftedit.DefaultCreatedAt = drafteditDescCreatedAt.Default.(func() time.Time)
	event.Policy = privacy.NewPolicies(schema.Event{})
	event.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := event.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescName is the schema descriptor for name field.
	eventDescName := eventFields[0].Descriptor()
	// event.NameValidator is a validator for the "name" field. It is called by the builders before save.
	event.NameValidator = func() func(string) error {
		validators := eventDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescPlannedStartDate is the schema descriptor for planned_start_date field.
	eventDescPlannedStartDate := eventFields[1].Descriptor()
	// event.PlannedStartDateValidator is a validator for the "planned_start_date" field. It is called by the builders before save.
	event.PlannedStartDateValidator = func() func(string) error {
		validators := eventDescPlannedStartDate.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(planned_start_date string) error {
			for _, fn := range fns {
				if err := fn(planned_start_date); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescPlannedEndDate is the schema descriptor for planned_end_date field.
	eventDescPlannedEndDate := eventFields[2].Descriptor()
	// event.PlannedEndDateValidator is a validator for the "planned_end_date" field. It is called by the builders before save.
	event.PlannedEndDateValidator = func() func(string) error {
		validators := eventDescPlannedEndDate.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(planned_end_date string) error {
			for _, fn := range fns {
				if err := fn(planned_end_date); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescTimezone is the schema descriptor for timezone field.
	eventDescTimezone := eventFields[3].Descriptor()
	// event.TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	event.TimezoneValidator = func() func(string) error {
		validators := eventDescTimezone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(timezone string) error {
			for _, fn := range fns {
				if err := fn(timezone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescEventLocale is the schema descriptor for event_locale field.
	eventDescEventLocale := eventFields[4].Descriptor()
	// event.EventLocaleValidator is a validator for the "event_locale" field. It is called by the builders before save.
	event.EventLocaleValidator = func() func(string) error {
		validators := eventDescEventLocale.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_locale string) error {
			for _, fn := range fns {
				if err := fn(event_locale); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescContentLanguage is the schema descriptor for content_language field.
	eventDescContentLanguage := eventFields[5].Descriptor()
	// event.ContentLanguageValidator is a validator for the "content_language" field. It is called by the builders before save.
	event.ContentLanguageValidator = eventDescContentLanguage.Validators[0].(func(string) error)
	// eventDescEventDayBoundary is the schema descriptor for event_day_boundary field.
	eventDescEventDayBoundary := eventFields[6].Descriptor()
	// event.EventDayBoundaryValidator is a validator for the "event_day_boundary" field. It is called by the builders before save.
	event.EventDayBoundaryValidator = func() func(string) error {
		validators := eventDescEventDayBoundary.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_day_boundary string) error {
			for _, fn := range fns {
				if err := fn(event_day_boundary); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescRevision is the schema descriptor for revision field.
	eventDescRevision := eventFields[7].Descriptor()
	// event.DefaultRevision holds the default value on creation for the revision field.
	event.DefaultRevision = eventDescRevision.Default.(int)
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[8].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	eventgrant.Policy = privacy.NewPolicies(schema.EventGrant{})
	eventgrant.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := eventgrant.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	eventgrantFields := schema.EventGrant{}.Fields()
	_ = eventgrantFields
	// eventgrantDescCreatedAt is the schema descriptor for created_at field.
	eventgrantDescCreatedAt := eventgrantFields[3].Descriptor()
	// eventgrant.DefaultCreatedAt holds the default value on creation for the created_at field.
	eventgrant.DefaultCreatedAt = eventgrantDescCreatedAt.Default.(func() time.Time)
	installation.Policy = privacy.NewPolicies(schema.Installation{})
	installation.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := installation.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	installationFields := schema.Installation{}.Fields()
	_ = installationFields
	// installationDescCreatedAt is the schema descriptor for created_at field.
	installationDescCreatedAt := installationFields[0].Descriptor()
	// installation.DefaultCreatedAt holds the default value on creation for the created_at field.
	installation.DefaultCreatedAt = installationDescCreatedAt.Default.(func() time.Time)
	// installationDescActivationGeneration is the schema descriptor for activation_generation field.
	installationDescActivationGeneration := installationFields[2].Descriptor()
	// installation.DefaultActivationGeneration holds the default value on creation for the activation_generation field.
	installation.DefaultActivationGeneration = installationDescActivationGeneration.Default.(int)
	// installation.ActivationGenerationValidator is a validator for the "activation_generation" field. It is called by the builders before save.
	installation.ActivationGenerationValidator = installationDescActivationGeneration.Validators[0].(func(int) error)
	lane.Policy = privacy.NewPolicies(schema.Lane{})
	lane.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := lane.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	laneFields := schema.Lane{}.Fields()
	_ = laneFields
	// laneDescCreatedAt is the schema descriptor for created_at field.
	laneDescCreatedAt := laneFields[1].Descriptor()
	// lane.DefaultCreatedAt holds the default value on creation for the created_at field.
	lane.DefaultCreatedAt = laneDescCreatedAt.Default.(func() time.Time)
	lanedraft.Policy = privacy.NewPolicies(schema.LaneDraft{})
	lanedraft.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := lanedraft.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	lanedraftHooks := schema.LaneDraft{}.Hooks()

	lanedraft.Hooks[1] = lanedraftHooks[0]
	lanedraftFields := schema.LaneDraft{}.Fields()
	_ = lanedraftFields
	// lanedraftDescName is the schema descriptor for name field.
	lanedraftDescName := lanedraftFields[2].Descriptor()
	// lanedraft.NameValidator is a validator for the "name" field. It is called by the builders before save.
	lanedraft.NameValidator = func() func(string) error {
		validators := lanedraftDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// lanedraftDescRetired is the schema descriptor for retired field.
	lanedraftDescRetired := lanedraftFields[3].Descriptor()
	// lanedraft.DefaultRetired holds the default value on creation for the retired field.
	lanedraft.DefaultRetired = lanedraftDescRetired.Default.(bool)
	lanepublishedversion.Policy = privacy.NewPolicies(schema.LanePublishedVersion{})
	lanepublishedversion.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := lanepublishedversion.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	lanepublishedversionHooks := schema.LanePublishedVersion{}.Hooks()

	lanepublishedversion.Hooks[1] = lanepublishedversionHooks[0]
	lanepublishedversionFields := schema.LanePublishedVersion{}.Fields()
	_ = lanepublishedversionFields
	// lanepublishedversionDescPublishedRevision is the schema descriptor for published_revision field.
	lanepublishedversionDescPublishedRevision := lanepublishedversionFields[2].Descriptor()
	// lanepublishedversion.PublishedRevisionValidator is a validator for the "published_revision" field. It is called by the builders before save.
	lanepublishedversion.PublishedRevisionValidator = lanepublishedversionDescPublishedRevision.Validators[0].(func(int) error)
	// lanepublishedversionDescName is the schema descriptor for name field.
	lanepublishedversionDescName := lanepublishedversionFields[3].Descriptor()
	// lanepublishedversion.NameValidator is a validator for the "name" field. It is called by the builders before save.
	lanepublishedversion.NameValidator = func() func(string) error {
		validators := lanepublishedversionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// lanepublishedversionDescRetired is the schema descriptor for retired field.
	lanepublishedversionDescRetired := lanepublishedversionFields[4].Descriptor()
	// lanepublishedversion.DefaultRetired holds the default value on creation for the retired field.
	lanepublishedversion.DefaultRetired = lanepublishedversionDescRetired.Default.(bool)
	// lanepublishedversionDescCreatedAt is the schema descriptor for created_at field.
	lanepublishedversionDescCreatedAt := lanepublishedversionFields[5].Descriptor()
	// lanepublishedversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	lanepublishedversion.DefaultCreatedAt = lanepublishedversionDescCreatedAt.Default.(func() time.Time)
	location.Policy = privacy.NewPolicies(schema.Location{})
	location.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := location.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	locationFields := schema.Location{}.Fields()
	_ = locationFields
	// locationDescCreatedAt is the schema descriptor for created_at field.
	locationDescCreatedAt := locationFields[1].Descriptor()
	// location.DefaultCreatedAt holds the default value on creation for the created_at field.
	location.DefaultCreatedAt = locationDescCreatedAt.Default.(func() time.Time)
	locationdraft.Policy = privacy.NewPolicies(schema.LocationDraft{})
	locationdraft.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := locationdraft.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	locationdraftFields := schema.LocationDraft{}.Fields()
	_ = locationdraftFields
	// locationdraftDescName is the schema descriptor for name field.
	locationdraftDescName := locationdraftFields[1].Descriptor()
	// locationdraft.NameValidator is a validator for the "name" field. It is called by the builders before save.
	locationdraft.NameValidator = func() func(string) error {
		validators := locationdraftDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// locationdraftDescRetired is the schema descriptor for retired field.
	locationdraftDescRetired := locationdraftFields[2].Descriptor()
	// locationdraft.DefaultRetired holds the default value on creation for the retired field.
	locationdraft.DefaultRetired = locationdraftDescRetired.Default.(bool)
	locationpublishedversion.Policy = privacy.NewPolicies(schema.LocationPublishedVersion{})
	locationpublishedversion.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := locationpublishedversion.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	locationpublishedversionFields := schema.LocationPublishedVersion{}.Fields()
	_ = locationpublishedversionFields
	// locationpublishedversionDescPublishedRevision is the schema descriptor for published_revision field.
	locationpublishedversionDescPublishedRevision := locationpublishedversionFields[1].Descriptor()
	// locationpublishedversion.PublishedRevisionValidator is a validator for the "published_revision" field. It is called by the builders before save.
	locationpublishedversion.PublishedRevisionValidator = locationpublishedversionDescPublishedRevision.Validators[0].(func(int) error)
	// locationpublishedversionDescName is the schema descriptor for name field.
	locationpublishedversionDescName := locationpublishedversionFields[2].Descriptor()
	// locationpublishedversion.NameValidator is a validator for the "name" field. It is called by the builders before save.
	locationpublishedversion.NameValidator = func() func(string) error {
		validators := locationpublishedversionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// locationpublishedversionDescRetired is the schema descriptor for retired field.
	locationpublishedversionDescRetired := locationpublishedversionFields[3].Descriptor()
	// locationpublishedversion.DefaultRetired holds the default value on creation for the retired field.
	locationpublishedversion.DefaultRetired = locationpublishedversionDescRetired.Default.(bool)
	// locationpublishedversionDescCreatedAt is the schema descriptor for created_at field.
	locationpublishedversionDescCreatedAt := locationpublishedversionFields[4].Descriptor()
	// locationpublishedversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	locationpublishedversion.DefaultCreatedAt = locationpublishedversionDescCreatedAt.Default.(func() time.Time)
	migrationFields := schema.Migration{}.Fields()
	_ = migrationFields
	// migrationDescVersion is the schema descriptor for version field.
	migrationDescVersion := migrationFields[0].Descriptor()
	// migration.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	migration.VersionValidator = migrationDescVersion.Validators[0].(func(int) error)
	// migrationDescName is the schema descriptor for name field.
	migrationDescName := migrationFields[1].Descriptor()
	// migration.NameValidator is a validator for the "name" field. It is called by the builders before save.
	migration.NameValidator = migrationDescName.Validators[0].(func(string) error)
	// migrationDescChecksum is the schema descriptor for checksum field.
	migrationDescChecksum := migrationFields[2].Descriptor()
	// migration.ChecksumValidator is a validator for the "checksum" field. It is called by the builders before save.
	migration.ChecksumValidator = func() func(string) error {
		validators := migrationDescChecksum.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(checksum string) error {
			for _, fn := range fns {
				if err := fn(checksum); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// migrationDescAppliedAt is the schema descriptor for applied_at field.
	migrationDescAppliedAt := migrationFields[3].Descriptor()
	// migration.DefaultAppliedAt holds the default value on creation for the applied_at field.
	migration.DefaultAppliedAt = migrationDescAppliedAt.Default.(func() time.Time)
	passwordcredential.Policy = privacy.NewPolicies(schema.PasswordCredential{})
	passwordcredential.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := passwordcredential.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	passwordcredentialFields := schema.PasswordCredential{}.Fields()
	_ = passwordcredentialFields
	// passwordcredentialDescPasswordHash is the schema descriptor for password_hash field.
	passwordcredentialDescPasswordHash := passwordcredentialFields[1].Descriptor()
	// passwordcredential.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	passwordcredential.PasswordHashValidator = passwordcredentialDescPasswordHash.Validators[0].(func(string) error)
	// passwordcredentialDescCreatedAt is the schema descriptor for created_at field.
	passwordcredentialDescCreatedAt := passwordcredentialFields[2].Descriptor()
	// passwordcredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordcredential.DefaultCreatedAt = passwordcredentialDescCreatedAt.Default.(func() time.Time)
	rundown.Policy = privacy.NewPolicies(schema.Rundown{})
	rundown.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := rundown.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	rundownFields := schema.Rundown{}.Fields()
	_ = rundownFields
	// rundownDescDraftRevision is the schema descriptor for draft_revision field.
	rundownDescDraftRevision := rundownFields[1].Descriptor()
	// rundown.DefaultDraftRevision holds the default value on creation for the draft_revision field.
	rundown.DefaultDraftRevision = rundownDescDraftRevision.Default.(int)
	// rundown.DraftRevisionValidator is a validator for the "draft_revision" field. It is called by the builders before save.
	rundown.DraftRevisionValidator = rundownDescDraftRevision.Validators[0].(func(int) error)
	// rundownDescPublishedRevision is the schema descriptor for published_revision field.
	rundownDescPublishedRevision := rundownFields[2].Descriptor()
	// rundown.DefaultPublishedRevision holds the default value on creation for the published_revision field.
	rundown.DefaultPublishedRevision = rundownDescPublishedRevision.Default.(int)
	// rundown.PublishedRevisionValidator is a validator for the "published_revision" field. It is called by the builders before save.
	rundown.PublishedRevisionValidator = rundownDescPublishedRevision.Validators[0].(func(int) error)
	session.Policy = privacy.NewPolicies(schema.Session{})
	session.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := session.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[1].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	sessiondraft.Policy = privacy.NewPolicies(schema.SessionDraft{})
	sessiondraft.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := sessiondraft.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	sessiondraftHooks := schema.SessionDraft{}.Hooks()

	sessiondraft.Hooks[1] = sessiondraftHooks[0]
	sessiondraftFields := schema.SessionDraft{}.Fields()
	_ = sessiondraftFields
	// sessiondraftDescTitle is the schema descriptor for title field.
	sessiondraftDescTitle := sessiondraftFields[1].Descriptor()
	// sessiondraft.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	sessiondraft.TitleValidator = func() func(string) error {
		validators := sessiondraftDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sessiondraftDescPublicDetails is the schema descriptor for public_details field.
	sessiondraftDescPublicDetails := sessiondraftFields[4].Descriptor()
	// sessiondraft.PublicDetailsValidator is a validator for the "public_details" field. It is called by the builders before save.
	sessiondraft.PublicDetailsValidator = sessiondraftDescPublicDetails.Validators[0].(func(string) error)
	// sessiondraftDescCrewNotes is the schema descriptor for crew_notes field.
	sessiondraftDescCrewNotes := sessiondraftFields[5].Descriptor()
	// sessiondraft.CrewNotesValidator is a validator for the "crew_notes" field. It is called by the builders before save.
	sessiondraft.CrewNotesValidator = sessiondraftDescCrewNotes.Validators[0].(func(string) error)
	// sessiondraftDescMinimumDurationSeconds is the schema descriptor for minimum_duration_seconds field.
	sessiondraftDescMinimumDurationSeconds := sessiondraftFields[9].Descriptor()
	// sessiondraft.MinimumDurationSecondsValidator is a validator for the "minimum_duration_seconds" field. It is called by the builders before save.
	sessiondraft.MinimumDurationSecondsValidator = sessiondraftDescMinimumDurationSeconds.Validators[0].(func(int) error)
	sessionpublishedversion.Policy = privacy.NewPolicies(schema.SessionPublishedVersion{})
	sessionpublishedversion.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := sessionpublishedversion.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	sessionpublishedversionHooks := schema.SessionPublishedVersion{}.Hooks()

	sessionpublishedversion.Hooks[1] = sessionpublishedversionHooks[0]
	sessionpublishedversionFields := schema.SessionPublishedVersion{}.Fields()
	_ = sessionpublishedversionFields
	// sessionpublishedversionDescPublishedRevision is the schema descriptor for published_revision field.
	sessionpublishedversionDescPublishedRevision := sessionpublishedversionFields[1].Descriptor()
	// sessionpublishedversion.PublishedRevisionValidator is a validator for the "published_revision" field. It is called by the builders before save.
	sessionpublishedversion.PublishedRevisionValidator = sessionpublishedversionDescPublishedRevision.Validators[0].(func(int) error)
	// sessionpublishedversionDescTitle is the schema descriptor for title field.
	sessionpublishedversionDescTitle := sessionpublishedversionFields[2].Descriptor()
	// sessionpublishedversion.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	sessionpublishedversion.TitleValidator = func() func(string) error {
		validators := sessionpublishedversionDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sessionpublishedversionDescPublicDetails is the schema descriptor for public_details field.
	sessionpublishedversionDescPublicDetails := sessionpublishedversionFields[5].Descriptor()
	// sessionpublishedversion.PublicDetailsValidator is a validator for the "public_details" field. It is called by the builders before save.
	sessionpublishedversion.PublicDetailsValidator = sessionpublishedversionDescPublicDetails.Validators[0].(func(string) error)
	// sessionpublishedversionDescCrewNotes is the schema descriptor for crew_notes field.
	sessionpublishedversionDescCrewNotes := sessionpublishedversionFields[6].Descriptor()
	// sessionpublishedversion.CrewNotesValidator is a validator for the "crew_notes" field. It is called by the builders before save.
	sessionpublishedversion.CrewNotesValidator = sessionpublishedversionDescCrewNotes.Validators[0].(func(string) error)
	// sessionpublishedversionDescMinimumDurationSeconds is the schema descriptor for minimum_duration_seconds field.
	sessionpublishedversionDescMinimumDurationSeconds := sessionpublishedversionFields[10].Descriptor()
	// sessionpublishedversion.MinimumDurationSecondsValidator is a validator for the "minimum_duration_seconds" field. It is called by the builders before save.
	sessionpublishedversion.MinimumDurationSecondsValidator = sessionpublishedversionDescMinimumDurationSeconds.Validators[0].(func(int) error)
	// sessionpublishedversionDescCreatedAt is the schema descriptor for created_at field.
	sessionpublishedversionDescCreatedAt := sessionpublishedversionFields[13].Descriptor()
	// sessionpublishedversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	sessionpublishedversion.DefaultCreatedAt = sessionpublishedversionDescCreatedAt.Default.(func() time.Time)
	track.Policy = privacy.NewPolicies(schema.Track{})
	track.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := track.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	trackFields := schema.Track{}.Fields()
	_ = trackFields
	// trackDescCreatedAt is the schema descriptor for created_at field.
	trackDescCreatedAt := trackFields[1].Descriptor()
	// track.DefaultCreatedAt holds the default value on creation for the created_at field.
	track.DefaultCreatedAt = trackDescCreatedAt.Default.(func() time.Time)
	trackdraft.Policy = privacy.NewPolicies(schema.TrackDraft{})
	trackdraft.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := trackdraft.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	trackdraftFields := schema.TrackDraft{}.Fields()
	_ = trackdraftFields
	// trackdraftDescName is the schema descriptor for name field.
	trackdraftDescName := trackdraftFields[1].Descriptor()
	// trackdraft.NameValidator is a validator for the "name" field. It is called by the builders before save.
	trackdraft.NameValidator = func() func(string) error {
		validators := trackdraftDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// trackdraftDescRetired is the schema descriptor for retired field.
	trackdraftDescRetired := trackdraftFields[2].Descriptor()
	// trackdraft.DefaultRetired holds the default value on creation for the retired field.
	trackdraft.DefaultRetired = trackdraftDescRetired.Default.(bool)
	trackpublishedversion.Policy = privacy.NewPolicies(schema.TrackPublishedVersion{})
	trackpublishedversion.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := trackpublishedversion.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	trackpublishedversionFields := schema.TrackPublishedVersion{}.Fields()
	_ = trackpublishedversionFields
	// trackpublishedversionDescPublishedRevision is the schema descriptor for published_revision field.
	trackpublishedversionDescPublishedRevision := trackpublishedversionFields[1].Descriptor()
	// trackpublishedversion.PublishedRevisionValidator is a validator for the "published_revision" field. It is called by the builders before save.
	trackpublishedversion.PublishedRevisionValidator = trackpublishedversionDescPublishedRevision.Validators[0].(func(int) error)
	// trackpublishedversionDescName is the schema descriptor for name field.
	trackpublishedversionDescName := trackpublishedversionFields[2].Descriptor()
	// trackpublishedversion.NameValidator is a validator for the "name" field. It is called by the builders before save.
	trackpublishedversion.NameValidator = func() func(string) error {
		validators := trackpublishedversionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// trackpublishedversionDescRetired is the schema descriptor for retired field.
	trackpublishedversionDescRetired := trackpublishedversionFields[3].Descriptor()
	// trackpublishedversion.DefaultRetired holds the default value on creation for the retired field.
	trackpublishedversion.DefaultRetired = trackpublishedversionDescRetired.Default.(bool)
	// trackpublishedversionDescCreatedAt is the schema descriptor for created_at field.
	trackpublishedversionDescCreatedAt := trackpublishedversionFields[4].Descriptor()
	// trackpublishedversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	trackpublishedversion.DefaultCreatedAt = trackpublishedversionDescCreatedAt.Default.(func() time.Time)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
