// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/account"
	"github.com/dotwaffle/beamers/ent/accountpreference"
	"github.com/dotwaffle/beamers/ent/accountprofile"
	"github.com/dotwaffle/beamers/ent/accountsession"
	"github.com/dotwaffle/beamers/ent/auditentry"
	"github.com/dotwaffle/beamers/ent/commandreceipt"
	"github.com/dotwaffle/beamers/ent/competitionentry"
	"github.com/dotwaffle/beamers/ent/draftedit"
	"github.com/dotwaffle/beamers/ent/eventgrant"
	"github.com/dotwaffle/beamers/ent/favoritesession"
	"github.com/dotwaffle/beamers/ent/federatedidentity"
	"github.com/dotwaffle/beamers/ent/passwordcredential"
	"github.com/dotwaffle/beamers/ent/recoverycode"
	"github.com/dotwaffle/beamers/ent/recoverytoken"
	"github.com/dotwaffle/beamers/ent/votingeligibility"
	"github.com/dotwaffle/beamers/ent/webauthncredential"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AccountCreate) SetName(v string) *AccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNormalizedName sets the "normalized_name" field.
func (_c *AccountCreate) SetNormalizedName(v string) *AccountCreate {
	_c.mutation.SetNormalizedName(v)
	return _c
}

// SetWebauthnUserHandle sets the "webauthn_user_handle" field.
func (_c *AccountCreate) SetWebauthnUserHandle(v []byte) *AccountCreate {
	_c.mutation.SetWebauthnUserHandle(v)
	return _c
}

// SetAdministrator sets the "administrator" field.
func (_c *AccountCreate) SetAdministrator(v bool) *AccountCreate {
	_c.mutation.SetAdministrator(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCreate) SetCreatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCreatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDisabledAt sets the "disabled_at" field.
func (_c *AccountCreate) SetDisabledAt(v time.Time) *AccountCreate {
	_c.mutation.SetDisabledAt(v)
	return _c
}

// SetNillableDisabledAt sets the "disabled_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableDisabledAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetDisabledAt(*v)
	}
	return _c
}

// SetPasswordCredentialID sets the "password_credential" edge to the PasswordCredential entity by ID.
func (_c *AccountCreate) SetPasswordCredentialID(id int) *AccountCreate {
	_c.mutation.SetPasswordCredentialID(id)
	return _c
}

// SetNillablePasswordCredentialID sets the "password_credential" edge to the PasswordCredential entity by ID if the given value is not nil.
func (_c *AccountCreate) SetNillablePasswordCredentialID(id *int) *AccountCreate {
	if id != nil {
		_c = _c.SetPasswordCredentialID(*id)
	}
	return _c
}

// SetPasswordCredential sets the "password_credential" edge to the PasswordCredential entity.
func (_c *AccountCreate) SetPasswordCredential(v *PasswordCredential) *AccountCreate {
	return _c.SetPasswordCredentialID(v.ID)
}

// AddWebauthnCredentialIDs adds the "webauthn_credentials" edge to the WebAuthnCredential entity by IDs.
func (_c *AccountCreate) AddWebauthnCredentialIDs(ids ...int) *AccountCreate {
	_c.mutation.AddWebauthnCredentialIDs(ids...)
	return _c
}

// AddWebauthnCredentials adds the "webauthn_credentials" edges to the WebAuthnCredential entity.
func (_c *AccountCreate) AddWebauthnCredentials(v ...*WebAuthnCredential) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWebauthnCredentialIDs(ids...)
}

// AddFederatedIdentityIDs adds the "federated_identities" edge to the FederatedIdentity entity by IDs.
func (_c *AccountCreate) AddFederatedIdentityIDs(ids ...int) *AccountCreate {
	_c.mutation.AddFederatedIdentityIDs(ids...)
	return _c
}

// AddFederatedIdentities adds the "federated_identities" edges to the FederatedIdentity entity.
func (_c *AccountCreate) AddFederatedIdentities(v ...*FederatedIdentity) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFederatedIdentityIDs(ids...)
}

// SetPreferenceID sets the "preference" edge to the AccountPreference entity by ID.
func (_c *AccountCreate) SetPreferenceID(id int) *AccountCreate {
	_c.mutation.SetPreferenceID(id)
	return _c
}

// SetNillablePreferenceID sets the "preference" edge to the AccountPreference entity by ID if the given value is not nil.
func (_c *AccountCreate) SetNillablePreferenceID(id *int) *AccountCreate {
	if id != nil {
		_c = _c.SetPreferenceID(*id)
	}
	return _c
}

// SetPreference sets the "preference" edge to the AccountPreference entity.
func (_c *AccountCreate) SetPreference(v *AccountPreference) *AccountCreate {
	return _c.SetPreferenceID(v.ID)
}

// SetProfileID sets the "profile" edge to the AccountProfile entity by ID.
func (_c *AccountCreate) SetProfileID(id int) *AccountCreate {
	_c.mutation.SetProfileID(id)
	return _c
}

// SetNillableProfileID sets the "profile" edge to the AccountProfile entity by ID if the given value is not nil.
func (_c *AccountCreate) SetNillableProfileID(id *int) *AccountCreate {
	if id != nil {
		_c = _c.SetProfileID(*id)
	}
	return _c
}

// SetProfile sets the "profile" edge to the AccountProfile entity.
func (_c *AccountCreate) SetProfile(v *AccountProfile) *AccountCreate {
	return _c.SetProfileID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the AccountSession entity by IDs.
func (_c *AccountCreate) AddSessionIDs(ids ...int) *AccountCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the AccountSession entity.
func (_c *AccountCreate) AddSessions(v ...*AccountSession) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// AddRecoveryCodeIDs adds the "recovery_codes" edge to the RecoveryCode entity by IDs.
func (_c *AccountCreate) AddRecoveryCodeIDs(ids ...int) *AccountCreate {
	_c.mutation.AddRecoveryCodeIDs(ids...)
	return _c
}

// AddRecoveryCodes adds the "recovery_codes" edges to the RecoveryCode entity.
func (_c *AccountCreate) AddRecoveryCodes(v ...*RecoveryCode) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecoveryCodeIDs(ids...)
}

// AddRecoveryTokenIDs adds the "recovery_tokens" edge to the RecoveryToken entity by IDs.
func (_c *AccountCreate) AddRecoveryTokenIDs(ids ...int) *AccountCreate {
	_c.mutation.AddRecoveryTokenIDs(ids...)
	return _c
}

// AddRecoveryTokens adds the "recovery_tokens" edges to the RecoveryToken entity.
func (_c *AccountCreate) AddRecoveryTokens(v ...*RecoveryToken) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecoveryTokenIDs(ids...)
}

// AddEventGrantIDs adds the "event_grants" edge to the EventGrant entity by IDs.
func (_c *AccountCreate) AddEventGrantIDs(ids ...int) *AccountCreate {
	_c.mutation.AddEventGrantIDs(ids...)
	return _c
}

// AddEventGrants adds the "event_grants" edges to the EventGrant entity.
func (_c *AccountCreate) AddEventGrants(v ...*EventGrant) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventGrantIDs(ids...)
}

// AddFavoriteSessionIDs adds the "favorite_sessions" edge to the FavoriteSession entity by IDs.
func (_c *AccountCreate) AddFavoriteSessionIDs(ids ...int) *AccountCreate {
	_c.mutation.AddFavoriteSessionIDs(ids...)
	return _c
}

// AddFavoriteSessions adds the "favorite_sessions" edges to the FavoriteSession entity.
func (_c *AccountCreate) AddFavoriteSessions(v ...*FavoriteSession) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFavoriteSessionIDs(ids...)
}

// AddCompetitionEntryIDs adds the "competition_entries" edge to the CompetitionEntry entity by IDs.
func (_c *AccountCreate) AddCompetitionEntryIDs(ids ...int) *AccountCreate {
	_c.mutation.AddCompetitionEntryIDs(ids...)
	return _c
}

// AddCompetitionEntries adds the "competition_entries" edges to the CompetitionEntry entity.
func (_c *AccountCreate) AddCompetitionEntries(v ...*CompetitionEntry) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCompetitionEntryIDs(ids...)
}

// AddVotingEligibilityIDs adds the "voting_eligibilities" edge to the VotingEligibility entity by IDs.
func (_c *AccountCreate) AddVotingEligibilityIDs(ids ...int) *AccountCreate {
	_c.mutation.AddVotingEligibilityIDs(ids...)
	return _c
}

// AddVotingEligibilities adds the "voting_eligibilities" edges to the VotingEligibility entity.
func (_c *AccountCreate) AddVotingEligibilities(v ...*VotingEligibility) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVotingEligibilityIDs(ids...)
}

// AddAuditEntryIDs adds the "audit_entries" edge to the AuditEntry entity by IDs.
func (_c *AccountCreate) AddAuditEntryIDs(ids ...int) *AccountCreate {
	_c.mutation.AddAuditEntryIDs(ids...)
	return _c
}

// AddAuditEntries adds the "audit_entries" edges to the AuditEntry entity.
func (_c *AccountCreate) AddAuditEntries(v ...*AuditEntry) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuditEntryIDs(ids...)
}

// AddCommandReceiptIDs adds the "command_receipts" edge to the CommandReceipt entity by IDs.
func (_c *AccountCreate) AddCommandReceiptIDs(ids ...int) *AccountCreate {
	_c.mutation.AddCommandReceiptIDs(ids...)
	return _c
}

// AddCommandReceipts adds the "command_receipts" edges to the CommandReceipt entity.
func (_c *AccountCreate) AddCommandReceipts(v ...*CommandReceipt) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommandReceiptIDs(ids...)
}

// AddDraftEditIDs adds the "draft_edits" edge to the DraftEdit entity by IDs.
func (_c *AccountCreate) AddDraftEditIDs(ids ...int) *AccountCreate {
	_c.mutation.AddDraftEditIDs(ids...)
	return _c
}

// AddDraftEdits adds the "draft_edits" edges to the DraftEdit entity.
func (_c *AccountCreate) AddDraftEdits(v ...*DraftEdit) *AccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDraftEditIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if account.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized account.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := account.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Account.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedName(); !ok {
		return &ValidationError{Name: "normalized_name", err: errors.New(`ent: missing required field "Account.normalized_name"`)}
	}
	if v, ok := _c.mutation.NormalizedName(); ok {
		if err := account.NormalizedNameValidator(v); err != nil {
			return &ValidationError{Name: "normalized_name", err: fmt.Errorf(`ent: validator failed for field "Account.normalized_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Administrator(); !ok {
		return &ValidationError{Name: "administrator", err: errors.New(`ent: missing required field "Account.administrator"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Account.created_at"`)}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NormalizedName(); ok {
		_spec.SetField(account.FieldNormalizedName, field.TypeString, value)
		_node.NormalizedName = value
	}
	if value, ok := _c.mutation.WebauthnUserHandle(); ok {
		_spec.SetField(account.FieldWebauthnUserHandle, field.TypeBytes, value)
		_node.WebauthnUserHandle = value
	}
	if value, ok := _c.mutation.Administrator(); ok {
		_spec.SetField(account.FieldAdministrator, field.TypeBool, value)
		_node.Administrator = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.DisabledAt(); ok {
		_spec.SetField(account.FieldDisabledAt, field.TypeTime, value)
		_node.DisabledAt = &value
	}
	if nodes := _c.mutation.PasswordCredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   account.PasswordCredentialTable,
			Columns: []string{account.PasswordCredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(passwordcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WebauthnCredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.WebauthnCredentialsTable,
			Columns: []string{account.WebauthnCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webauthncredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FederatedIdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.FederatedIdentitiesTable,
			Columns: []string{account.FederatedIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(federatedidentity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PreferenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   account.PreferenceTable,
			Columns: []string{account.PreferenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountpreference.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   account.ProfileTable,
			Columns: []string{account.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.SessionsTable,
			Columns: []string{account.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecoveryCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.RecoveryCodesTable,
			Columns: []string{account.RecoveryCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recoverycode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecoveryTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.RecoveryTokensTable,
			Columns: []string{account.RecoveryTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recoverytoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventGrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.EventGrantsTable,
			Columns: []string{account.EventGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventgrant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FavoriteSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.FavoriteSessionsTable,
			Columns: []string{account.FavoriteSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(favoritesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CompetitionEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.CompetitionEntriesTable,
			Columns: []string{account.CompetitionEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competitionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VotingEligibilitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.VotingEligibilitiesTable,
			Columns: []string{account.VotingEligibilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votingeligibility.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuditEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.AuditEntriesTable,
			Columns: []string{account.AuditEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommandReceiptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.CommandReceiptsTable,
			Columns: []string{account.CommandReceiptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commandreceipt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DraftEditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.DraftEditsTable,
			Columns: []string{account.DraftEditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(draftedit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
