// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/account"
	"github.com/dotwaffle/beamers/ent/auditentry"
)

// AuditEntryCreate is the builder for creating a AuditEntry entity.
type AuditEntryCreate struct {
	config
	mutation *AuditEntryMutation
	hooks    []Hook
}

// SetActorAccountID sets the "actor_account_id" field.
func (_c *AuditEntryCreate) SetActorAccountID(v int) *AuditEntryCreate {
	_c.mutation.SetActorAccountID(v)
	return _c
}

// SetNillableActorAccountID sets the "actor_account_id" field if the given value is not nil.
func (_c *AuditEntryCreate) SetNillableActorAccountID(v *int) *AuditEntryCreate {
	if v != nil {
		_c.SetActorAccountID(*v)
	}
	return _c
}

// SetActorKind sets the "actor_kind" field.
func (_c *AuditEntryCreate) SetActorKind(v auditentry.ActorKind) *AuditEntryCreate {
	_c.mutation.SetActorKind(v)
	return _c
}

// SetNillableActorKind sets the "actor_kind" field if the given value is not nil.
func (_c *AuditEntryCreate) SetNillableActorKind(v *auditentry.ActorKind) *AuditEntryCreate {
	if v != nil {
		_c.SetActorKind(*v)
	}
	return _c
}

// SetActorUploadLinkID sets the "actor_upload_link_id" field.
func (_c *AuditEntryCreate) SetActorUploadLinkID(v int) *AuditEntryCreate {
	_c.mutation.SetActorUploadLinkID(v)
	return _c
}

// SetNillableActorUploadLinkID sets the "actor_upload_link_id" field if the given value is not nil.
func (_c *AuditEntryCreate) SetNillableActorUploadLinkID(v *int) *AuditEntryCreate {
	if v != nil {
		_c.SetActorUploadLinkID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditEntryCreate) SetCreatedAt(v time.Time) *AuditEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditEntryCreate) SetNillableCreatedAt(v *time.Time) *AuditEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AuditEntryCreate) SetAction(v string) *AuditEntryCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *AuditEntryCreate) SetTargetType(v string) *AuditEntryCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *AuditEntryCreate) SetTargetID(v string) *AuditEntryCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *AuditEntryCreate) SetResult(v auditentry.Result) *AuditEntryCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *AuditEntryCreate) SetReason(v string) *AuditEntryCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *AuditEntryCreate) SetNillableReason(v *string) *AuditEntryCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *AuditEntryCreate) SetNote(v string) *AuditEntryCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *AuditEntryCreate) SetNillableNote(v *string) *AuditEntryCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetActorID sets the "actor" edge to the Account entity by ID.
func (_c *AuditEntryCreate) SetActorID(id int) *AuditEntryCreate {
	_c.mutation.SetActorID(id)
	return _c
}

// SetNillableActorID sets the "actor" edge to the Account entity by ID if the given value is not nil.
func (_c *AuditEntryCreate) SetNillableActorID(id *int) *AuditEntryCreate {
	if id != nil {
		_c = _c.SetActorID(*id)
	}
	return _c
}

// SetActor sets the "actor" edge to the Account entity.
func (_c *AuditEntryCreate) SetActor(v *Account) *AuditEntryCreate {
	return _c.SetActorID(v.ID)
}

// Mutation returns the AuditEntryMutation object of the builder.
func (_c *AuditEntryCreate) Mutation() *AuditEntryMutation {
	return _c.mutation
}

// Save creates the AuditEntry in the database.
func (_c *AuditEntryCreate) Save(ctx context.Context) (*AuditEntry, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditEntryCreate) SaveX(ctx context.Context) *AuditEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditEntryCreate) defaults() error {
	if _, ok := _c.mutation.ActorKind(); !ok {
		v := auditentry.DefaultActorKind
		_c.mutation.SetActorKind(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if auditentry.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized auditentry.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := auditentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditEntryCreate) check() error {
	if _, ok := _c.mutation.ActorKind(); !ok {
		return &ValidationError{Name: "actor_kind", err: errors.New(`ent: missing required field "AuditEntry.actor_kind"`)}
	}
	if v, ok := _c.mutation.ActorKind(); ok {
		if err := auditentry.ActorKindValidator(v); err != nil {
			return &ValidationError{Name: "actor_kind", err: fmt.Errorf(`ent: validator failed for field "AuditEntry.actor_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditEntry.created_at"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AuditEntry.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := auditentry.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditEntry.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "AuditEntry.target_type"`)}
	}
	if v, ok := _c.mutation.TargetType(); ok {
		if err := auditentry.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "AuditEntry.target_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "AuditEntry.target_id"`)}
	}
	if v, ok := _c.mutation.TargetID(); ok {
		if err := auditentry.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "AuditEntry.target_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "AuditEntry.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := auditentry.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "AuditEntry.result": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := auditentry.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AuditEntry.reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Note(); ok {
		if err := auditentry.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "AuditEntry.note": %w`, err)}
		}
	}
	return nil
}

func (_c *AuditEntryCreate) sqlSave(ctx context.Context) (*AuditEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditEntryCreate) createSpec() (*AuditEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditentry.Table, sqlgraph.NewFieldSpec(auditentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ActorKind(); ok {
		_spec.SetField(auditentry.FieldActorKind, field.TypeEnum, value)
		_node.ActorKind = value
	}
	if value, ok := _c.mutation.ActorUploadLinkID(); ok {
		_spec.SetField(auditentry.FieldActorUploadLinkID, field.TypeInt, value)
		_node.ActorUploadLinkID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(auditentry.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(auditentry.FieldTargetType, field.TypeString, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(auditentry.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(auditentry.FieldResult, field.TypeEnum, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(auditentry.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(auditentry.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if nodes := _c.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditentry.ActorTable,
			Columns: []string{auditentry.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActorAccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuditEntryCreateBulk is the builder for creating many AuditEntry entities in bulk.
type AuditEntryCreateBulk struct {
	config
	err      error
	builders []*AuditEntryCreate
}

// Save creates the AuditEntry entities in the database.
func (_c *AuditEntryCreateBulk) Save(ctx context.Context) ([]*AuditEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditEntryCreateBulk) SaveX(ctx context.Context) []*AuditEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
