// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/displayoverride"
	"github.com/dotwaffle/beamers/ent/displayoverridestate"
	"github.com/dotwaffle/beamers/ent/predicate"
)

// DisplayOverrideStateUpdate is the builder for updating DisplayOverrideState entities.
type DisplayOverrideStateUpdate struct {
	config
	hooks    []Hook
	mutation *DisplayOverrideStateMutation
}

// Where appends a list predicates to the DisplayOverrideStateUpdate builder.
func (_u *DisplayOverrideStateUpdate) Where(ps ...predicate.DisplayOverrideState) *DisplayOverrideStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOverrideID sets the "override_id" field.
func (_u *DisplayOverrideStateUpdate) SetOverrideID(v int) *DisplayOverrideStateUpdate {
	_u.mutation.SetOverrideID(v)
	return _u
}

// SetNillableOverrideID sets the "override_id" field if the given value is not nil.
func (_u *DisplayOverrideStateUpdate) SetNillableOverrideID(v *int) *DisplayOverrideStateUpdate {
	if v != nil {
		_u.SetOverrideID(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *DisplayOverrideStateUpdate) SetRevision(v int) *DisplayOverrideStateUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *DisplayOverrideStateUpdate) SetNillableRevision(v *int) *DisplayOverrideStateUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *DisplayOverrideStateUpdate) AddRevision(v int) *DisplayOverrideStateUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DisplayOverrideStateUpdate) SetUpdatedAt(v time.Time) *DisplayOverrideStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DisplayOverrideStateUpdate) SetNillableUpdatedAt(v *time.Time) *DisplayOverrideStateUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetOverride sets the "override" edge to the DisplayOverride entity.
func (_u *DisplayOverrideStateUpdate) SetOverride(v *DisplayOverride) *DisplayOverrideStateUpdate {
	return _u.SetOverrideID(v.ID)
}

// Mutation returns the DisplayOverrideStateMutation object of the builder.
func (_u *DisplayOverrideStateUpdate) Mutation() *DisplayOverrideStateMutation {
	return _u.mutation
}

// ClearOverride clears the "override" edge to the DisplayOverride entity.
func (_u *DisplayOverrideStateUpdate) ClearOverride() *DisplayOverrideStateUpdate {
	_u.mutation.ClearOverride()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DisplayOverrideStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DisplayOverrideStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DisplayOverrideStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DisplayOverrideStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DisplayOverrideStateUpdate) check() error {
	if v, ok := _u.mutation.Revision(); ok {
		if err := displayoverridestate.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "DisplayOverrideState.revision": %w`, err)}
		}
	}
	if _u.mutation.DisplayCleared() && len(_u.mutation.DisplayIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DisplayOverrideState.display"`)
	}
	if _u.mutation.OverrideCleared() && len(_u.mutation.OverrideIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DisplayOverrideState.override"`)
	}
	return nil
}

func (_u *DisplayOverrideStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(displayoverridestate.Table, displayoverridestate.Columns, sqlgraph.NewFieldSpec(displayoverridestate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(displayoverridestate.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(displayoverridestate.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(displayoverridestate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OverrideCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   displayoverridestate.OverrideTable,
			Columns: []string{displayoverridestate.OverrideColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(displayoverride.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OverrideIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   displayoverridestate.OverrideTable,
			Columns: []string{displayoverridestate.OverrideColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(displayoverride.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{displayoverridestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DisplayOverrideStateUpdateOne is the builder for updating a single DisplayOverrideState entity.
type DisplayOverrideStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DisplayOverrideStateMutation
}

// SetOverrideID sets the "override_id" field.
func (_u *DisplayOverrideStateUpdateOne) SetOverrideID(v int) *DisplayOverrideStateUpdateOne {
	_u.mutation.SetOverrideID(v)
	return _u
}

// SetNillableOverrideID sets the "override_id" field if the given value is not nil.
func (_u *DisplayOverrideStateUpdateOne) SetNillableOverrideID(v *int) *DisplayOverrideStateUpdateOne {
	if v != nil {
		_u.SetOverrideID(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *DisplayOverrideStateUpdateOne) SetRevision(v int) *DisplayOverrideStateUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *DisplayOverrideStateUpdateOne) SetNillableRevision(v *int) *DisplayOverrideStateUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *DisplayOverrideStateUpdateOne) AddRevision(v int) *DisplayOverrideStateUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DisplayOverrideStateUpdateOne) SetUpdatedAt(v time.Time) *DisplayOverrideStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DisplayOverrideStateUpdateOne) SetNillableUpdatedAt(v *time.Time) *DisplayOverrideStateUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetOverride sets the "override" edge to the DisplayOverride entity.
func (_u *DisplayOverrideStateUpdateOne) SetOverride(v *DisplayOverride) *DisplayOverrideStateUpdateOne {
	return _u.SetOverrideID(v.ID)
}

// Mutation returns the DisplayOverrideStateMutation object of the builder.
func (_u *DisplayOverrideStateUpdateOne) Mutation() *DisplayOverrideStateMutation {
	return _u.mutation
}

// ClearOverride clears the "override" edge to the DisplayOverride entity.
func (_u *DisplayOverrideStateUpdateOne) ClearOverride() *DisplayOverrideStateUpdateOne {
	_u.mutation.ClearOverride()
	return _u
}

// Where appends a list predicates to the DisplayOverrideStateUpdate builder.
func (_u *DisplayOverrideStateUpdateOne) Where(ps ...predicate.DisplayOverrideState) *DisplayOverrideStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DisplayOverrideStateUpdateOne) Select(field string, fields ...string) *DisplayOverrideStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DisplayOverrideState entity.
func (_u *DisplayOverrideStateUpdateOne) Save(ctx context.Context) (*DisplayOverrideState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DisplayOverrideStateUpdateOne) SaveX(ctx context.Context) *DisplayOverrideState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DisplayOverrideStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DisplayOverrideStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DisplayOverrideStateUpdateOne) check() error {
	if v, ok := _u.mutation.Revision(); ok {
		if err := displayoverridestate.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "DisplayOverrideState.revision": %w`, err)}
		}
	}
	if _u.mutation.DisplayCleared() && len(_u.mutation.DisplayIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DisplayOverrideState.display"`)
	}
	if _u.mutation.OverrideCleared() && len(_u.mutation.OverrideIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DisplayOverrideState.override"`)
	}
	return nil
}

func (_u *DisplayOverrideStateUpdateOne) sqlSave(ctx context.Context) (_node *DisplayOverrideState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(displayoverridestate.Table, displayoverridestate.Columns, sqlgraph.NewFieldSpec(displayoverridestate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DisplayOverrideState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, displayoverridestate.FieldID)
		for _, f := range fields {
			if !displayoverridestate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != displayoverridestate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(displayoverridestate.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(displayoverridestate.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(displayoverridestate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OverrideCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   displayoverridestate.OverrideTable,
			Columns: []string{displayoverridestate.OverrideColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(displayoverride.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OverrideIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   displayoverridestate.OverrideTable,
			Columns: []string{displayoverridestate.OverrideColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(displayoverride.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DisplayOverrideState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{displayoverridestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
