// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/eventslug"
	"github.com/dotwaffle/beamers/ent/predicate"
)

// EventSlugDelete is the builder for deleting a EventSlug entity.
type EventSlugDelete struct {
	config
	hooks    []Hook
	mutation *EventSlugMutation
}

// Where appends a list predicates to the EventSlugDelete builder.
func (_d *EventSlugDelete) Where(ps ...predicate.EventSlug) *EventSlugDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EventSlugDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EventSlugDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EventSlugDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(eventslug.Table, sqlgraph.NewFieldSpec(eventslug.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EventSlugDeleteOne is the builder for deleting a single EventSlug entity.
type EventSlugDeleteOne struct {
	_d *EventSlugDelete
}

// Where appends a list predicates to the EventSlugDelete builder.
func (_d *EventSlugDeleteOne) Where(ps ...predicate.EventSlug) *EventSlugDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EventSlugDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventslug.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EventSlugDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
