// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/lane"
	"github.com/dotwaffle/beamers/ent/lanedraft"
	"github.com/dotwaffle/beamers/ent/lanepublishedversion"
	"github.com/dotwaffle/beamers/ent/predicate"
	"github.com/dotwaffle/beamers/ent/sessiondraft"
	"github.com/dotwaffle/beamers/ent/sessionpublishedversion"
)

// LaneUpdate is the builder for updating Lane entities.
type LaneUpdate struct {
	config
	hooks    []Hook
	mutation *LaneMutation
}

// Where appends a list predicates to the LaneUpdate builder.
func (_u *LaneUpdate) Where(ps ...predicate.Lane) *LaneUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDraftID sets the "draft" edge to the LaneDraft entity by ID.
func (_u *LaneUpdate) SetDraftID(id int) *LaneUpdate {
	_u.mutation.SetDraftID(id)
	return _u
}

// SetNillableDraftID sets the "draft" edge to the LaneDraft entity by ID if the given value is not nil.
func (_u *LaneUpdate) SetNillableDraftID(id *int) *LaneUpdate {
	if id != nil {
		_u = _u.SetDraftID(*id)
	}
	return _u
}

// SetDraft sets the "draft" edge to the LaneDraft entity.
func (_u *LaneUpdate) SetDraft(v *LaneDraft) *LaneUpdate {
	return _u.SetDraftID(v.ID)
}

// AddPublishedVersionIDs adds the "published_versions" edge to the LanePublishedVersion entity by IDs.
func (_u *LaneUpdate) AddPublishedVersionIDs(ids ...int) *LaneUpdate {
	_u.mutation.AddPublishedVersionIDs(ids...)
	return _u
}

// AddPublishedVersions adds the "published_versions" edges to the LanePublishedVersion entity.
func (_u *LaneUpdate) AddPublishedVersions(v ...*LanePublishedVersion) *LaneUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublishedVersionIDs(ids...)
}

// AddSessionDraftIDs adds the "session_drafts" edge to the SessionDraft entity by IDs.
func (_u *LaneUpdate) AddSessionDraftIDs(ids ...int) *LaneUpdate {
	_u.mutation.AddSessionDraftIDs(ids...)
	return _u
}

// AddSessionDrafts adds the "session_drafts" edges to the SessionDraft entity.
func (_u *LaneUpdate) AddSessionDrafts(v ...*SessionDraft) *LaneUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionDraftIDs(ids...)
}

// AddSessionPublishedVersionIDs adds the "session_published_versions" edge to the SessionPublishedVersion entity by IDs.
func (_u *LaneUpdate) AddSessionPublishedVersionIDs(ids ...int) *LaneUpdate {
	_u.mutation.AddSessionPublishedVersionIDs(ids...)
	return _u
}

// AddSessionPublishedVersions adds the "session_published_versions" edges to the SessionPublishedVersion entity.
func (_u *LaneUpdate) AddSessionPublishedVersions(v ...*SessionPublishedVersion) *LaneUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionPublishedVersionIDs(ids...)
}

// Mutation returns the LaneMutation object of the builder.
func (_u *LaneUpdate) Mutation() *LaneMutation {
	return _u.mutation
}

// ClearDraft clears the "draft" edge to the LaneDraft entity.
func (_u *LaneUpdate) ClearDraft() *LaneUpdate {
	_u.mutation.ClearDraft()
	return _u
}

// ClearPublishedVersions clears all "published_versions" edges to the LanePublishedVersion entity.
func (_u *LaneUpdate) ClearPublishedVersions() *LaneUpdate {
	_u.mutation.ClearPublishedVersions()
	return _u
}

// RemovePublishedVersionIDs removes the "published_versions" edge to LanePublishedVersion entities by IDs.
func (_u *LaneUpdate) RemovePublishedVersionIDs(ids ...int) *LaneUpdate {
	_u.mutation.RemovePublishedVersionIDs(ids...)
	return _u
}

// RemovePublishedVersions removes "published_versions" edges to LanePublishedVersion entities.
func (_u *LaneUpdate) RemovePublishedVersions(v ...*LanePublishedVersion) *LaneUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublishedVersionIDs(ids...)
}

// ClearSessionDrafts clears all "session_drafts" edges to the SessionDraft entity.
func (_u *LaneUpdate) ClearSessionDrafts() *LaneUpdate {
	_u.mutation.ClearSessionDrafts()
	return _u
}

// RemoveSessionDraftIDs removes the "session_drafts" edge to SessionDraft entities by IDs.
func (_u *LaneUpdate) RemoveSessionDraftIDs(ids ...int) *LaneUpdate {
	_u.mutation.RemoveSessionDraftIDs(ids...)
	return _u
}

// RemoveSessionDrafts removes "session_drafts" edges to SessionDraft entities.
func (_u *LaneUpdate) RemoveSessionDrafts(v ...*SessionDraft) *LaneUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionDraftIDs(ids...)
}

// ClearSessionPublishedVersions clears all "session_published_versions" edges to the SessionPublishedVersion entity.
func (_u *LaneUpdate) ClearSessionPublishedVersions() *LaneUpdate {
	_u.mutation.ClearSessionPublishedVersions()
	return _u
}

// RemoveSessionPublishedVersionIDs removes the "session_published_versions" edge to SessionPublishedVersion entities by IDs.
func (_u *LaneUpdate) RemoveSessionPublishedVersionIDs(ids ...int) *LaneUpdate {
	_u.mutation.RemoveSessionPublishedVersionIDs(ids...)
	return _u
}

// RemoveSessionPublishedVersions removes "session_published_versions" edges to SessionPublishedVersion entities.
func (_u *LaneUpdate) RemoveSessionPublishedVersions(v ...*SessionPublishedVersion) *LaneUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionPublishedVersionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LaneUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LaneUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LaneUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LaneUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LaneUpdate) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Lane.event"`)
	}
	return nil
}

func (_u *LaneUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lane.Table, lane.Columns, sqlgraph.NewFieldSpec(lane.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.DraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lane.DraftTable,
			Columns: []string{lane.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lane.DraftTable,
			Columns: []string{lane.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lane.PublishedVersionsTable,
			Columns: []string{lane.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lane.PublishedVersionsTable,
			Columns: []string{lane.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lane.PublishedVersionsTable,
			Columns: []string{lane.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionDraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionDraftsTable,
			Columns: lane.SessionDraftsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionDraftsIDs(); len(nodes) > 0 && !_u.mutation.SessionDraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionDraftsTable,
			Columns: lane.SessionDraftsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionDraftsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionDraftsTable,
			Columns: lane.SessionDraftsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionPublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionPublishedVersionsTable,
			Columns: lane.SessionPublishedVersionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionPublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.SessionPublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionPublishedVersionsTable,
			Columns: lane.SessionPublishedVersionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionPublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionPublishedVersionsTable,
			Columns: lane.SessionPublishedVersionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lane.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LaneUpdateOne is the builder for updating a single Lane entity.
type LaneUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LaneMutation
}

// SetDraftID sets the "draft" edge to the LaneDraft entity by ID.
func (_u *LaneUpdateOne) SetDraftID(id int) *LaneUpdateOne {
	_u.mutation.SetDraftID(id)
	return _u
}

// SetNillableDraftID sets the "draft" edge to the LaneDraft entity by ID if the given value is not nil.
func (_u *LaneUpdateOne) SetNillableDraftID(id *int) *LaneUpdateOne {
	if id != nil {
		_u = _u.SetDraftID(*id)
	}
	return _u
}

// SetDraft sets the "draft" edge to the LaneDraft entity.
func (_u *LaneUpdateOne) SetDraft(v *LaneDraft) *LaneUpdateOne {
	return _u.SetDraftID(v.ID)
}

// AddPublishedVersionIDs adds the "published_versions" edge to the LanePublishedVersion entity by IDs.
func (_u *LaneUpdateOne) AddPublishedVersionIDs(ids ...int) *LaneUpdateOne {
	_u.mutation.AddPublishedVersionIDs(ids...)
	return _u
}

// AddPublishedVersions adds the "published_versions" edges to the LanePublishedVersion entity.
func (_u *LaneUpdateOne) AddPublishedVersions(v ...*LanePublishedVersion) *LaneUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublishedVersionIDs(ids...)
}

// AddSessionDraftIDs adds the "session_drafts" edge to the SessionDraft entity by IDs.
func (_u *LaneUpdateOne) AddSessionDraftIDs(ids ...int) *LaneUpdateOne {
	_u.mutation.AddSessionDraftIDs(ids...)
	return _u
}

// AddSessionDrafts adds the "session_drafts" edges to the SessionDraft entity.
func (_u *LaneUpdateOne) AddSessionDrafts(v ...*SessionDraft) *LaneUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionDraftIDs(ids...)
}

// AddSessionPublishedVersionIDs adds the "session_published_versions" edge to the SessionPublishedVersion entity by IDs.
func (_u *LaneUpdateOne) AddSessionPublishedVersionIDs(ids ...int) *LaneUpdateOne {
	_u.mutation.AddSessionPublishedVersionIDs(ids...)
	return _u
}

// AddSessionPublishedVersions adds the "session_published_versions" edges to the SessionPublishedVersion entity.
func (_u *LaneUpdateOne) AddSessionPublishedVersions(v ...*SessionPublishedVersion) *LaneUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionPublishedVersionIDs(ids...)
}

// Mutation returns the LaneMutation object of the builder.
func (_u *LaneUpdateOne) Mutation() *LaneMutation {
	return _u.mutation
}

// ClearDraft clears the "draft" edge to the LaneDraft entity.
func (_u *LaneUpdateOne) ClearDraft() *LaneUpdateOne {
	_u.mutation.ClearDraft()
	return _u
}

// ClearPublishedVersions clears all "published_versions" edges to the LanePublishedVersion entity.
func (_u *LaneUpdateOne) ClearPublishedVersions() *LaneUpdateOne {
	_u.mutation.ClearPublishedVersions()
	return _u
}

// RemovePublishedVersionIDs removes the "published_versions" edge to LanePublishedVersion entities by IDs.
func (_u *LaneUpdateOne) RemovePublishedVersionIDs(ids ...int) *LaneUpdateOne {
	_u.mutation.RemovePublishedVersionIDs(ids...)
	return _u
}

// RemovePublishedVersions removes "published_versions" edges to LanePublishedVersion entities.
func (_u *LaneUpdateOne) RemovePublishedVersions(v ...*LanePublishedVersion) *LaneUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublishedVersionIDs(ids...)
}

// ClearSessionDrafts clears all "session_drafts" edges to the SessionDraft entity.
func (_u *LaneUpdateOne) ClearSessionDrafts() *LaneUpdateOne {
	_u.mutation.ClearSessionDrafts()
	return _u
}

// RemoveSessionDraftIDs removes the "session_drafts" edge to SessionDraft entities by IDs.
func (_u *LaneUpdateOne) RemoveSessionDraftIDs(ids ...int) *LaneUpdateOne {
	_u.mutation.RemoveSessionDraftIDs(ids...)
	return _u
}

// RemoveSessionDrafts removes "session_drafts" edges to SessionDraft entities.
func (_u *LaneUpdateOne) RemoveSessionDrafts(v ...*SessionDraft) *LaneUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionDraftIDs(ids...)
}

// ClearSessionPublishedVersions clears all "session_published_versions" edges to the SessionPublishedVersion entity.
func (_u *LaneUpdateOne) ClearSessionPublishedVersions() *LaneUpdateOne {
	_u.mutation.ClearSessionPublishedVersions()
	return _u
}

// RemoveSessionPublishedVersionIDs removes the "session_published_versions" edge to SessionPublishedVersion entities by IDs.
func (_u *LaneUpdateOne) RemoveSessionPublishedVersionIDs(ids ...int) *LaneUpdateOne {
	_u.mutation.RemoveSessionPublishedVersionIDs(ids...)
	return _u
}

// RemoveSessionPublishedVersions removes "session_published_versions" edges to SessionPublishedVersion entities.
func (_u *LaneUpdateOne) RemoveSessionPublishedVersions(v ...*SessionPublishedVersion) *LaneUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionPublishedVersionIDs(ids...)
}

// Where appends a list predicates to the LaneUpdate builder.
func (_u *LaneUpdateOne) Where(ps ...predicate.Lane) *LaneUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LaneUpdateOne) Select(field string, fields ...string) *LaneUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Lane entity.
func (_u *LaneUpdateOne) Save(ctx context.Context) (*Lane, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LaneUpdateOne) SaveX(ctx context.Context) *Lane {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LaneUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LaneUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LaneUpdateOne) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Lane.event"`)
	}
	return nil
}

func (_u *LaneUpdateOne) sqlSave(ctx context.Context) (_node *Lane, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lane.Table, lane.Columns, sqlgraph.NewFieldSpec(lane.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Lane.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lane.FieldID)
		for _, f := range fields {
			if !lane.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lane.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.DraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lane.DraftTable,
			Columns: []string{lane.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   lane.DraftTable,
			Columns: []string{lane.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lane.PublishedVersionsTable,
			Columns: []string{lane.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lane.PublishedVersionsTable,
			Columns: []string{lane.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lane.PublishedVersionsTable,
			Columns: []string{lane.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionDraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionDraftsTable,
			Columns: lane.SessionDraftsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionDraftsIDs(); len(nodes) > 0 && !_u.mutation.SessionDraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionDraftsTable,
			Columns: lane.SessionDraftsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionDraftsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionDraftsTable,
			Columns: lane.SessionDraftsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionPublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionPublishedVersionsTable,
			Columns: lane.SessionPublishedVersionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionPublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.SessionPublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionPublishedVersionsTable,
			Columns: lane.SessionPublishedVersionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionPublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   lane.SessionPublishedVersionsTable,
			Columns: lane.SessionPublishedVersionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Lane{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lane.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
