// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/lanedraft"
	"github.com/dotwaffle/beamers/ent/lanepublishedversion"
	"github.com/dotwaffle/beamers/ent/location"
	"github.com/dotwaffle/beamers/ent/locationdraft"
	"github.com/dotwaffle/beamers/ent/locationpublishedversion"
	"github.com/dotwaffle/beamers/ent/predicate"
)

// LocationUpdate is the builder for updating Location entities.
type LocationUpdate struct {
	config
	hooks    []Hook
	mutation *LocationMutation
}

// Where appends a list predicates to the LocationUpdate builder.
func (_u *LocationUpdate) Where(ps ...predicate.Location) *LocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDraftID sets the "draft" edge to the LocationDraft entity by ID.
func (_u *LocationUpdate) SetDraftID(id int) *LocationUpdate {
	_u.mutation.SetDraftID(id)
	return _u
}

// SetNillableDraftID sets the "draft" edge to the LocationDraft entity by ID if the given value is not nil.
func (_u *LocationUpdate) SetNillableDraftID(id *int) *LocationUpdate {
	if id != nil {
		_u = _u.SetDraftID(*id)
	}
	return _u
}

// SetDraft sets the "draft" edge to the LocationDraft entity.
func (_u *LocationUpdate) SetDraft(v *LocationDraft) *LocationUpdate {
	return _u.SetDraftID(v.ID)
}

// AddPublishedVersionIDs adds the "published_versions" edge to the LocationPublishedVersion entity by IDs.
func (_u *LocationUpdate) AddPublishedVersionIDs(ids ...int) *LocationUpdate {
	_u.mutation.AddPublishedVersionIDs(ids...)
	return _u
}

// AddPublishedVersions adds the "published_versions" edges to the LocationPublishedVersion entity.
func (_u *LocationUpdate) AddPublishedVersions(v ...*LocationPublishedVersion) *LocationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublishedVersionIDs(ids...)
}

// AddLaneDraftIDs adds the "lane_drafts" edge to the LaneDraft entity by IDs.
func (_u *LocationUpdate) AddLaneDraftIDs(ids ...int) *LocationUpdate {
	_u.mutation.AddLaneDraftIDs(ids...)
	return _u
}

// AddLaneDrafts adds the "lane_drafts" edges to the LaneDraft entity.
func (_u *LocationUpdate) AddLaneDrafts(v ...*LaneDraft) *LocationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLaneDraftIDs(ids...)
}

// AddLanePublishedVersionIDs adds the "lane_published_versions" edge to the LanePublishedVersion entity by IDs.
func (_u *LocationUpdate) AddLanePublishedVersionIDs(ids ...int) *LocationUpdate {
	_u.mutation.AddLanePublishedVersionIDs(ids...)
	return _u
}

// AddLanePublishedVersions adds the "lane_published_versions" edges to the LanePublishedVersion entity.
func (_u *LocationUpdate) AddLanePublishedVersions(v ...*LanePublishedVersion) *LocationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLanePublishedVersionIDs(ids...)
}

// Mutation returns the LocationMutation object of the builder.
func (_u *LocationUpdate) Mutation() *LocationMutation {
	return _u.mutation
}

// ClearDraft clears the "draft" edge to the LocationDraft entity.
func (_u *LocationUpdate) ClearDraft() *LocationUpdate {
	_u.mutation.ClearDraft()
	return _u
}

// ClearPublishedVersions clears all "published_versions" edges to the LocationPublishedVersion entity.
func (_u *LocationUpdate) ClearPublishedVersions() *LocationUpdate {
	_u.mutation.ClearPublishedVersions()
	return _u
}

// RemovePublishedVersionIDs removes the "published_versions" edge to LocationPublishedVersion entities by IDs.
func (_u *LocationUpdate) RemovePublishedVersionIDs(ids ...int) *LocationUpdate {
	_u.mutation.RemovePublishedVersionIDs(ids...)
	return _u
}

// RemovePublishedVersions removes "published_versions" edges to LocationPublishedVersion entities.
func (_u *LocationUpdate) RemovePublishedVersions(v ...*LocationPublishedVersion) *LocationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublishedVersionIDs(ids...)
}

// ClearLaneDrafts clears all "lane_drafts" edges to the LaneDraft entity.
func (_u *LocationUpdate) ClearLaneDrafts() *LocationUpdate {
	_u.mutation.ClearLaneDrafts()
	return _u
}

// RemoveLaneDraftIDs removes the "lane_drafts" edge to LaneDraft entities by IDs.
func (_u *LocationUpdate) RemoveLaneDraftIDs(ids ...int) *LocationUpdate {
	_u.mutation.RemoveLaneDraftIDs(ids...)
	return _u
}

// RemoveLaneDrafts removes "lane_drafts" edges to LaneDraft entities.
func (_u *LocationUpdate) RemoveLaneDrafts(v ...*LaneDraft) *LocationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLaneDraftIDs(ids...)
}

// ClearLanePublishedVersions clears all "lane_published_versions" edges to the LanePublishedVersion entity.
func (_u *LocationUpdate) ClearLanePublishedVersions() *LocationUpdate {
	_u.mutation.ClearLanePublishedVersions()
	return _u
}

// RemoveLanePublishedVersionIDs removes the "lane_published_versions" edge to LanePublishedVersion entities by IDs.
func (_u *LocationUpdate) RemoveLanePublishedVersionIDs(ids ...int) *LocationUpdate {
	_u.mutation.RemoveLanePublishedVersionIDs(ids...)
	return _u
}

// RemoveLanePublishedVersions removes "lane_published_versions" edges to LanePublishedVersion entities.
func (_u *LocationUpdate) RemoveLanePublishedVersions(v ...*LanePublishedVersion) *LocationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLanePublishedVersionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationUpdate) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Location.event"`)
	}
	return nil
}

func (_u *LocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(location.Table, location.Columns, sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.DraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   location.DraftTable,
			Columns: []string{location.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationdraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   location.DraftTable,
			Columns: []string{location.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationdraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.PublishedVersionsTable,
			Columns: []string{location.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationpublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.PublishedVersionsTable,
			Columns: []string{location.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.PublishedVersionsTable,
			Columns: []string{location.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LaneDraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LaneDraftsTable,
			Columns: []string{location.LaneDraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLaneDraftsIDs(); len(nodes) > 0 && !_u.mutation.LaneDraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LaneDraftsTable,
			Columns: []string{location.LaneDraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LaneDraftsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LaneDraftsTable,
			Columns: []string{location.LaneDraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LanePublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LanePublishedVersionsTable,
			Columns: []string{location.LanePublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLanePublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.LanePublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LanePublishedVersionsTable,
			Columns: []string{location.LanePublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LanePublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LanePublishedVersionsTable,
			Columns: []string{location.LanePublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LocationUpdateOne is the builder for updating a single Location entity.
type LocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocationMutation
}

// SetDraftID sets the "draft" edge to the LocationDraft entity by ID.
func (_u *LocationUpdateOne) SetDraftID(id int) *LocationUpdateOne {
	_u.mutation.SetDraftID(id)
	return _u
}

// SetNillableDraftID sets the "draft" edge to the LocationDraft entity by ID if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableDraftID(id *int) *LocationUpdateOne {
	if id != nil {
		_u = _u.SetDraftID(*id)
	}
	return _u
}

// SetDraft sets the "draft" edge to the LocationDraft entity.
func (_u *LocationUpdateOne) SetDraft(v *LocationDraft) *LocationUpdateOne {
	return _u.SetDraftID(v.ID)
}

// AddPublishedVersionIDs adds the "published_versions" edge to the LocationPublishedVersion entity by IDs.
func (_u *LocationUpdateOne) AddPublishedVersionIDs(ids ...int) *LocationUpdateOne {
	_u.mutation.AddPublishedVersionIDs(ids...)
	return _u
}

// AddPublishedVersions adds the "published_versions" edges to the LocationPublishedVersion entity.
func (_u *LocationUpdateOne) AddPublishedVersions(v ...*LocationPublishedVersion) *LocationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublishedVersionIDs(ids...)
}

// AddLaneDraftIDs adds the "lane_drafts" edge to the LaneDraft entity by IDs.
func (_u *LocationUpdateOne) AddLaneDraftIDs(ids ...int) *LocationUpdateOne {
	_u.mutation.AddLaneDraftIDs(ids...)
	return _u
}

// AddLaneDrafts adds the "lane_drafts" edges to the LaneDraft entity.
func (_u *LocationUpdateOne) AddLaneDrafts(v ...*LaneDraft) *LocationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLaneDraftIDs(ids...)
}

// AddLanePublishedVersionIDs adds the "lane_published_versions" edge to the LanePublishedVersion entity by IDs.
func (_u *LocationUpdateOne) AddLanePublishedVersionIDs(ids ...int) *LocationUpdateOne {
	_u.mutation.AddLanePublishedVersionIDs(ids...)
	return _u
}

// AddLanePublishedVersions adds the "lane_published_versions" edges to the LanePublishedVersion entity.
func (_u *LocationUpdateOne) AddLanePublishedVersions(v ...*LanePublishedVersion) *LocationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLanePublishedVersionIDs(ids...)
}

// Mutation returns the LocationMutation object of the builder.
func (_u *LocationUpdateOne) Mutation() *LocationMutation {
	return _u.mutation
}

// ClearDraft clears the "draft" edge to the LocationDraft entity.
func (_u *LocationUpdateOne) ClearDraft() *LocationUpdateOne {
	_u.mutation.ClearDraft()
	return _u
}

// ClearPublishedVersions clears all "published_versions" edges to the LocationPublishedVersion entity.
func (_u *LocationUpdateOne) ClearPublishedVersions() *LocationUpdateOne {
	_u.mutation.ClearPublishedVersions()
	return _u
}

// RemovePublishedVersionIDs removes the "published_versions" edge to LocationPublishedVersion entities by IDs.
func (_u *LocationUpdateOne) RemovePublishedVersionIDs(ids ...int) *LocationUpdateOne {
	_u.mutation.RemovePublishedVersionIDs(ids...)
	return _u
}

// RemovePublishedVersions removes "published_versions" edges to LocationPublishedVersion entities.
func (_u *LocationUpdateOne) RemovePublishedVersions(v ...*LocationPublishedVersion) *LocationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublishedVersionIDs(ids...)
}

// ClearLaneDrafts clears all "lane_drafts" edges to the LaneDraft entity.
func (_u *LocationUpdateOne) ClearLaneDrafts() *LocationUpdateOne {
	_u.mutation.ClearLaneDrafts()
	return _u
}

// RemoveLaneDraftIDs removes the "lane_drafts" edge to LaneDraft entities by IDs.
func (_u *LocationUpdateOne) RemoveLaneDraftIDs(ids ...int) *LocationUpdateOne {
	_u.mutation.RemoveLaneDraftIDs(ids...)
	return _u
}

// RemoveLaneDrafts removes "lane_drafts" edges to LaneDraft entities.
func (_u *LocationUpdateOne) RemoveLaneDrafts(v ...*LaneDraft) *LocationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLaneDraftIDs(ids...)
}

// ClearLanePublishedVersions clears all "lane_published_versions" edges to the LanePublishedVersion entity.
func (_u *LocationUpdateOne) ClearLanePublishedVersions() *LocationUpdateOne {
	_u.mutation.ClearLanePublishedVersions()
	return _u
}

// RemoveLanePublishedVersionIDs removes the "lane_published_versions" edge to LanePublishedVersion entities by IDs.
func (_u *LocationUpdateOne) RemoveLanePublishedVersionIDs(ids ...int) *LocationUpdateOne {
	_u.mutation.RemoveLanePublishedVersionIDs(ids...)
	return _u
}

// RemoveLanePublishedVersions removes "lane_published_versions" edges to LanePublishedVersion entities.
func (_u *LocationUpdateOne) RemoveLanePublishedVersions(v ...*LanePublishedVersion) *LocationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLanePublishedVersionIDs(ids...)
}

// Where appends a list predicates to the LocationUpdate builder.
func (_u *LocationUpdateOne) Where(ps ...predicate.Location) *LocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LocationUpdateOne) Select(field string, fields ...string) *LocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Location entity.
func (_u *LocationUpdateOne) Save(ctx context.Context) (*Location, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationUpdateOne) SaveX(ctx context.Context) *Location {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LocationUpdateOne) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Location.event"`)
	}
	return nil
}

func (_u *LocationUpdateOne) sqlSave(ctx context.Context) (_node *Location, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(location.Table, location.Columns, sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Location.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, location.FieldID)
		for _, f := range fields {
			if !location.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != location.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.DraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   location.DraftTable,
			Columns: []string{location.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationdraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   location.DraftTable,
			Columns: []string{location.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationdraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.PublishedVersionsTable,
			Columns: []string{location.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationpublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.PublishedVersionsTable,
			Columns: []string{location.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.PublishedVersionsTable,
			Columns: []string{location.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(locationpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LaneDraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LaneDraftsTable,
			Columns: []string{location.LaneDraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLaneDraftsIDs(); len(nodes) > 0 && !_u.mutation.LaneDraftsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LaneDraftsTable,
			Columns: []string{location.LaneDraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LaneDraftsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LaneDraftsTable,
			Columns: []string{location.LaneDraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanedraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LanePublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LanePublishedVersionsTable,
			Columns: []string{location.LanePublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLanePublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.LanePublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LanePublishedVersionsTable,
			Columns: []string{location.LanePublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LanePublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.LanePublishedVersionsTable,
			Columns: []string{location.LanePublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lanepublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Location{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
