// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/event"
	"github.com/dotwaffle/beamers/ent/predicate"
	"github.com/dotwaffle/beamers/ent/prizegiving"
	"github.com/dotwaffle/beamers/ent/session"
)

// PrizegivingQuery is the builder for querying Prizegiving entities.
type PrizegivingQuery struct {
	config
	ctx          *QueryContext
	order        []prizegiving.OrderOption
	inters       []Interceptor
	predicates   []predicate.Prizegiving
	withEvent    *EventQuery
	withCeremony *SessionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PrizegivingQuery builder.
func (_q *PrizegivingQuery) Where(ps ...predicate.Prizegiving) *PrizegivingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PrizegivingQuery) Limit(limit int) *PrizegivingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PrizegivingQuery) Offset(offset int) *PrizegivingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PrizegivingQuery) Unique(unique bool) *PrizegivingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PrizegivingQuery) Order(o ...prizegiving.OrderOption) *PrizegivingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEvent chains the current query on the "event" edge.
func (_q *PrizegivingQuery) QueryEvent() *EventQuery {
	query := (&EventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(prizegiving.Table, prizegiving.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, prizegiving.EventTable, prizegiving.EventColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCeremony chains the current query on the "ceremony" edge.
func (_q *PrizegivingQuery) QueryCeremony() *SessionQuery {
	query := (&SessionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(prizegiving.Table, prizegiving.FieldID, selector),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, prizegiving.CeremonyTable, prizegiving.CeremonyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Prizegiving entity from the query.
// Returns a *NotFoundError when no Prizegiving was found.
func (_q *PrizegivingQuery) First(ctx context.Context) (*Prizegiving, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{prizegiving.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PrizegivingQuery) FirstX(ctx context.Context) *Prizegiving {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Prizegiving ID from the query.
// Returns a *NotFoundError when no Prizegiving ID was found.
func (_q *PrizegivingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{prizegiving.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PrizegivingQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Prizegiving entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Prizegiving entity is found.
// Returns a *NotFoundError when no Prizegiving entities are found.
func (_q *PrizegivingQuery) Only(ctx context.Context) (*Prizegiving, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{prizegiving.Label}
	default:
		return nil, &NotSingularError{prizegiving.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PrizegivingQuery) OnlyX(ctx context.Context) *Prizegiving {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Prizegiving ID in the query.
// Returns a *NotSingularError when more than one Prizegiving ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PrizegivingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{prizegiving.Label}
	default:
		err = &NotSingularError{prizegiving.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PrizegivingQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Prizegivings.
func (_q *PrizegivingQuery) All(ctx context.Context) ([]*Prizegiving, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Prizegiving, *PrizegivingQuery]()
	return withInterceptors[[]*Prizegiving](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PrizegivingQuery) AllX(ctx context.Context) []*Prizegiving {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Prizegiving IDs.
func (_q *PrizegivingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(prizegiving.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PrizegivingQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PrizegivingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PrizegivingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PrizegivingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PrizegivingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PrizegivingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PrizegivingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PrizegivingQuery) Clone() *PrizegivingQuery {
	if _q == nil {
		return nil
	}
	return &PrizegivingQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]prizegiving.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Prizegiving{}, _q.predicates...),
		withEvent:    _q.withEvent.Clone(),
		withCeremony: _q.withCeremony.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrizegivingQuery) WithEvent(opts ...func(*EventQuery)) *PrizegivingQuery {
	query := (&EventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvent = query
	return _q
}

// WithCeremony tells the query-builder to eager-load the nodes that are connected to
// the "ceremony" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PrizegivingQuery) WithCeremony(opts ...func(*SessionQuery)) *PrizegivingQuery {
	query := (&SessionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCeremony = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventID int `json:"event_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Prizegiving.Query().
//		GroupBy(prizegiving.FieldEventID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PrizegivingQuery) GroupBy(field string, fields ...string) *PrizegivingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PrizegivingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = prizegiving.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventID int `json:"event_id,omitempty"`
//	}
//
//	client.Prizegiving.Query().
//		Select(prizegiving.FieldEventID).
//		Scan(ctx, &v)
func (_q *PrizegivingQuery) Select(fields ...string) *PrizegivingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PrizegivingSelect{PrizegivingQuery: _q}
	sbuild.label = prizegiving.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PrizegivingSelect configured with the given aggregations.
func (_q *PrizegivingQuery) Aggregate(fns ...AggregateFunc) *PrizegivingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PrizegivingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !prizegiving.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if prizegiving.Policy == nil {
		return errors.New("ent: uninitialized prizegiving.Policy (forgotten import ent/runtime?)")
	}
	if err := prizegiving.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *PrizegivingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Prizegiving, error) {
	var (
		nodes       = []*Prizegiving{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withEvent != nil,
			_q.withCeremony != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Prizegiving).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Prizegiving{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEvent; query != nil {
		if err := _q.loadEvent(ctx, query, nodes, nil,
			func(n *Prizegiving, e *Event) { n.Edges.Event = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCeremony; query != nil {
		if err := _q.loadCeremony(ctx, query, nodes, nil,
			func(n *Prizegiving, e *Session) { n.Edges.Ceremony = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PrizegivingQuery) loadEvent(ctx context.Context, query *EventQuery, nodes []*Prizegiving, init func(*Prizegiving), assign func(*Prizegiving, *Event)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Prizegiving)
	for i := range nodes {
		fk := nodes[i].EventID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(event.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "event_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PrizegivingQuery) loadCeremony(ctx context.Context, query *SessionQuery, nodes []*Prizegiving, init func(*Prizegiving), assign func(*Prizegiving, *Session)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Prizegiving)
	for i := range nodes {
		fk := nodes[i].CeremonySessionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(session.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ceremony_session_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PrizegivingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PrizegivingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(prizegiving.Table, prizegiving.Columns, sqlgraph.NewFieldSpec(prizegiving.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prizegiving.FieldID)
		for i := range fields {
			if fields[i] != prizegiving.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withEvent != nil {
			_spec.Node.AddColumnOnce(prizegiving.FieldEventID)
		}
		if _q.withCeremony != nil {
			_spec.Node.AddColumnOnce(prizegiving.FieldCeremonySessionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PrizegivingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(prizegiving.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = prizegiving.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PrizegivingGroupBy is the group-by builder for Prizegiving entities.
type PrizegivingGroupBy struct {
	selector
	build *PrizegivingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PrizegivingGroupBy) Aggregate(fns ...AggregateFunc) *PrizegivingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PrizegivingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrizegivingQuery, *PrizegivingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PrizegivingGroupBy) sqlScan(ctx context.Context, root *PrizegivingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PrizegivingSelect is the builder for selecting fields of Prizegiving entities.
type PrizegivingSelect struct {
	*PrizegivingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PrizegivingSelect) Aggregate(fns ...AggregateFunc) *PrizegivingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PrizegivingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PrizegivingQuery, *PrizegivingSelect](ctx, _s.PrizegivingQuery, _s, _s.inters, v)
}

func (_s *PrizegivingSelect) sqlScan(ctx context.Context, root *PrizegivingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
