// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/predicate"
	"github.com/dotwaffle/beamers/ent/registrationpolicy"
)

// RegistrationPolicyUpdate is the builder for updating RegistrationPolicy entities.
type RegistrationPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *RegistrationPolicyMutation
}

// Where appends a list predicates to the RegistrationPolicyUpdate builder.
func (_u *RegistrationPolicyUpdate) Where(ps ...predicate.RegistrationPolicy) *RegistrationPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRegistrationOpen sets the "registration_open" field.
func (_u *RegistrationPolicyUpdate) SetRegistrationOpen(v bool) *RegistrationPolicyUpdate {
	_u.mutation.SetRegistrationOpen(v)
	return _u
}

// SetNillableRegistrationOpen sets the "registration_open" field if the given value is not nil.
func (_u *RegistrationPolicyUpdate) SetNillableRegistrationOpen(v *bool) *RegistrationPolicyUpdate {
	if v != nil {
		_u.SetRegistrationOpen(*v)
	}
	return _u
}

// Mutation returns the RegistrationPolicyMutation object of the builder.
func (_u *RegistrationPolicyUpdate) Mutation() *RegistrationPolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RegistrationPolicyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegistrationPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RegistrationPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegistrationPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RegistrationPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(registrationpolicy.Table, registrationpolicy.Columns, sqlgraph.NewFieldSpec(registrationpolicy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RegistrationOpen(); ok {
		_spec.SetField(registrationpolicy.FieldRegistrationOpen, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registrationpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RegistrationPolicyUpdateOne is the builder for updating a single RegistrationPolicy entity.
type RegistrationPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RegistrationPolicyMutation
}

// SetRegistrationOpen sets the "registration_open" field.
func (_u *RegistrationPolicyUpdateOne) SetRegistrationOpen(v bool) *RegistrationPolicyUpdateOne {
	_u.mutation.SetRegistrationOpen(v)
	return _u
}

// SetNillableRegistrationOpen sets the "registration_open" field if the given value is not nil.
func (_u *RegistrationPolicyUpdateOne) SetNillableRegistrationOpen(v *bool) *RegistrationPolicyUpdateOne {
	if v != nil {
		_u.SetRegistrationOpen(*v)
	}
	return _u
}

// Mutation returns the RegistrationPolicyMutation object of the builder.
func (_u *RegistrationPolicyUpdateOne) Mutation() *RegistrationPolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the RegistrationPolicyUpdate builder.
func (_u *RegistrationPolicyUpdateOne) Where(ps ...predicate.RegistrationPolicy) *RegistrationPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RegistrationPolicyUpdateOne) Select(field string, fields ...string) *RegistrationPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RegistrationPolicy entity.
func (_u *RegistrationPolicyUpdateOne) Save(ctx context.Context) (*RegistrationPolicy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegistrationPolicyUpdateOne) SaveX(ctx context.Context) *RegistrationPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RegistrationPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegistrationPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RegistrationPolicyUpdateOne) sqlSave(ctx context.Context) (_node *RegistrationPolicy, err error) {
	_spec := sqlgraph.NewUpdateSpec(registrationpolicy.Table, registrationpolicy.Columns, sqlgraph.NewFieldSpec(registrationpolicy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RegistrationPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, registrationpolicy.FieldID)
		for _, f := range fields {
			if !registrationpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != registrationpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RegistrationOpen(); ok {
		_spec.SetField(registrationpolicy.FieldRegistrationOpen, field.TypeBool, value)
	}
	_node = &RegistrationPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registrationpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
