// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/releasedprofileentry"
)

// ReleasedProfileEntryCreate is the builder for creating a ReleasedProfileEntry entity.
type ReleasedProfileEntryCreate struct {
	config
	mutation *ReleasedProfileEntryMutation
	hooks    []Hook
}

// SetEntryID sets the "entry_id" field.
func (_c *ReleasedProfileEntryCreate) SetEntryID(v int) *ReleasedProfileEntryCreate {
	_c.mutation.SetEntryID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ReleasedProfileEntryCreate) SetName(v string) *ReleasedProfileEntryCreate {
	_c.mutation.SetName(v)
	return _c
}

// Mutation returns the ReleasedProfileEntryMutation object of the builder.
func (_c *ReleasedProfileEntryCreate) Mutation() *ReleasedProfileEntryMutation {
	return _c.mutation
}

// Save creates the ReleasedProfileEntry in the database.
func (_c *ReleasedProfileEntryCreate) Save(ctx context.Context) (*ReleasedProfileEntry, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReleasedProfileEntryCreate) SaveX(ctx context.Context) *ReleasedProfileEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReleasedProfileEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReleasedProfileEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReleasedProfileEntryCreate) check() error {
	if _, ok := _c.mutation.EntryID(); !ok {
		return &ValidationError{Name: "entry_id", err: errors.New(`ent: missing required field "ReleasedProfileEntry.entry_id"`)}
	}
	if v, ok := _c.mutation.EntryID(); ok {
		if err := releasedprofileentry.EntryIDValidator(v); err != nil {
			return &ValidationError{Name: "entry_id", err: fmt.Errorf(`ent: validator failed for field "ReleasedProfileEntry.entry_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ReleasedProfileEntry.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := releasedprofileentry.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ReleasedProfileEntry.name": %w`, err)}
		}
	}
	return nil
}

func (_c *ReleasedProfileEntryCreate) sqlSave(ctx context.Context) (*ReleasedProfileEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReleasedProfileEntryCreate) createSpec() (*ReleasedProfileEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &ReleasedProfileEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(releasedprofileentry.Table, sqlgraph.NewFieldSpec(releasedprofileentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EntryID(); ok {
		_spec.SetField(releasedprofileentry.FieldEntryID, field.TypeInt, value)
		_node.EntryID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(releasedprofileentry.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// ReleasedProfileEntryCreateBulk is the builder for creating many ReleasedProfileEntry entities in bulk.
type ReleasedProfileEntryCreateBulk struct {
	config
	err      error
	builders []*ReleasedProfileEntryCreate
}

// Save creates the ReleasedProfileEntry entities in the database.
func (_c *ReleasedProfileEntryCreateBulk) Save(ctx context.Context) ([]*ReleasedProfileEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReleasedProfileEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReleasedProfileEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReleasedProfileEntryCreateBulk) SaveX(ctx context.Context) []*ReleasedProfileEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReleasedProfileEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReleasedProfileEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
