// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/event"
	"github.com/dotwaffle/beamers/ent/rundown"
)

// RundownCreate is the builder for creating a Rundown entity.
type RundownCreate struct {
	config
	mutation *RundownMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (_c *RundownCreate) SetEventID(v int) *RundownCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetDraftRevision sets the "draft_revision" field.
func (_c *RundownCreate) SetDraftRevision(v int) *RundownCreate {
	_c.mutation.SetDraftRevision(v)
	return _c
}

// SetNillableDraftRevision sets the "draft_revision" field if the given value is not nil.
func (_c *RundownCreate) SetNillableDraftRevision(v *int) *RundownCreate {
	if v != nil {
		_c.SetDraftRevision(*v)
	}
	return _c
}

// SetPublishedRevision sets the "published_revision" field.
func (_c *RundownCreate) SetPublishedRevision(v int) *RundownCreate {
	_c.mutation.SetPublishedRevision(v)
	return _c
}

// SetNillablePublishedRevision sets the "published_revision" field if the given value is not nil.
func (_c *RundownCreate) SetNillablePublishedRevision(v *int) *RundownCreate {
	if v != nil {
		_c.SetPublishedRevision(*v)
	}
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *RundownCreate) SetEvent(v *Event) *RundownCreate {
	return _c.SetEventID(v.ID)
}

// Mutation returns the RundownMutation object of the builder.
func (_c *RundownCreate) Mutation() *RundownMutation {
	return _c.mutation
}

// Save creates the Rundown in the database.
func (_c *RundownCreate) Save(ctx context.Context) (*Rundown, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RundownCreate) SaveX(ctx context.Context) *Rundown {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RundownCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RundownCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RundownCreate) defaults() error {
	if _, ok := _c.mutation.DraftRevision(); !ok {
		v := rundown.DefaultDraftRevision
		_c.mutation.SetDraftRevision(v)
	}
	if _, ok := _c.mutation.PublishedRevision(); !ok {
		v := rundown.DefaultPublishedRevision
		_c.mutation.SetPublishedRevision(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RundownCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "Rundown.event_id"`)}
	}
	if _, ok := _c.mutation.DraftRevision(); !ok {
		return &ValidationError{Name: "draft_revision", err: errors.New(`ent: missing required field "Rundown.draft_revision"`)}
	}
	if v, ok := _c.mutation.DraftRevision(); ok {
		if err := rundown.DraftRevisionValidator(v); err != nil {
			return &ValidationError{Name: "draft_revision", err: fmt.Errorf(`ent: validator failed for field "Rundown.draft_revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublishedRevision(); !ok {
		return &ValidationError{Name: "published_revision", err: errors.New(`ent: missing required field "Rundown.published_revision"`)}
	}
	if v, ok := _c.mutation.PublishedRevision(); ok {
		if err := rundown.PublishedRevisionValidator(v); err != nil {
			return &ValidationError{Name: "published_revision", err: fmt.Errorf(`ent: validator failed for field "Rundown.published_revision": %w`, err)}
		}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "Rundown.event"`)}
	}
	return nil
}

func (_c *RundownCreate) sqlSave(ctx context.Context) (*Rundown, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RundownCreate) createSpec() (*Rundown, *sqlgraph.CreateSpec) {
	var (
		_node = &Rundown{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rundown.Table, sqlgraph.NewFieldSpec(rundown.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DraftRevision(); ok {
		_spec.SetField(rundown.FieldDraftRevision, field.TypeInt, value)
		_node.DraftRevision = value
	}
	if value, ok := _c.mutation.PublishedRevision(); ok {
		_spec.SetField(rundown.FieldPublishedRevision, field.TypeInt, value)
		_node.PublishedRevision = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   rundown.EventTable,
			Columns: []string{rundown.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RundownCreateBulk is the builder for creating many Rundown entities in bulk.
type RundownCreateBulk struct {
	config
	err      error
	builders []*RundownCreate
}

// Save creates the Rundown entities in the database.
func (_c *RundownCreateBulk) Save(ctx context.Context) ([]*Rundown, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Rundown, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RundownMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RundownCreateBulk) SaveX(ctx context.Context) []*Rundown {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RundownCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RundownCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
