// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/lane"
	"github.com/dotwaffle/beamers/ent/location"
	"github.com/dotwaffle/beamers/ent/session"
	"github.com/dotwaffle/beamers/ent/sessionpublishedversion"
	"github.com/dotwaffle/beamers/ent/track"
)

// SessionPublishedVersionCreate is the builder for creating a SessionPublishedVersion entity.
type SessionPublishedVersionCreate struct {
	config
	mutation *SessionPublishedVersionMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *SessionPublishedVersionCreate) SetSessionID(v int) *SessionPublishedVersionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetPublishedRevision sets the "published_revision" field.
func (_c *SessionPublishedVersionCreate) SetPublishedRevision(v int) *SessionPublishedVersionCreate {
	_c.mutation.SetPublishedRevision(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *SessionPublishedVersionCreate) SetTitle(v string) *SessionPublishedVersionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSpeaker sets the "speaker" field.
func (_c *SessionPublishedVersionCreate) SetSpeaker(v string) *SessionPublishedVersionCreate {
	_c.mutation.SetSpeaker(v)
	return _c
}

// SetNillableSpeaker sets the "speaker" field if the given value is not nil.
func (_c *SessionPublishedVersionCreate) SetNillableSpeaker(v *string) *SessionPublishedVersionCreate {
	if v != nil {
		_c.SetSpeaker(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *SessionPublishedVersionCreate) SetType(v sessionpublishedversion.Type) *SessionPublishedVersionCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetAudienceVisibility sets the "audience_visibility" field.
func (_c *SessionPublishedVersionCreate) SetAudienceVisibility(v sessionpublishedversion.AudienceVisibility) *SessionPublishedVersionCreate {
	_c.mutation.SetAudienceVisibility(v)
	return _c
}

// SetPublicDetails sets the "public_details" field.
func (_c *SessionPublishedVersionCreate) SetPublicDetails(v string) *SessionPublishedVersionCreate {
	_c.mutation.SetPublicDetails(v)
	return _c
}

// SetNillablePublicDetails sets the "public_details" field if the given value is not nil.
func (_c *SessionPublishedVersionCreate) SetNillablePublicDetails(v *string) *SessionPublishedVersionCreate {
	if v != nil {
		_c.SetPublicDetails(*v)
	}
	return _c
}

// SetCrewNotes sets the "crew_notes" field.
func (_c *SessionPublishedVersionCreate) SetCrewNotes(v string) *SessionPublishedVersionCreate {
	_c.mutation.SetCrewNotes(v)
	return _c
}

// SetNillableCrewNotes sets the "crew_notes" field if the given value is not nil.
func (_c *SessionPublishedVersionCreate) SetNillableCrewNotes(v *string) *SessionPublishedVersionCreate {
	if v != nil {
		_c.SetCrewNotes(*v)
	}
	return _c
}

// SetPlannedStart sets the "planned_start" field.
func (_c *SessionPublishedVersionCreate) SetPlannedStart(v time.Time) *SessionPublishedVersionCreate {
	_c.mutation.SetPlannedStart(v)
	return _c
}

// SetPlannedEnd sets the "planned_end" field.
func (_c *SessionPublishedVersionCreate) SetPlannedEnd(v time.Time) *SessionPublishedVersionCreate {
	_c.mutation.SetPlannedEnd(v)
	return _c
}

// SetTimingPolicy sets the "timing_policy" field.
func (_c *SessionPublishedVersionCreate) SetTimingPolicy(v sessionpublishedversion.TimingPolicy) *SessionPublishedVersionCreate {
	_c.mutation.SetTimingPolicy(v)
	return _c
}

// SetMinimumDurationSeconds sets the "minimum_duration_seconds" field.
func (_c *SessionPublishedVersionCreate) SetMinimumDurationSeconds(v int) *SessionPublishedVersionCreate {
	_c.mutation.SetMinimumDurationSeconds(v)
	return _c
}

// SetStartBoundary sets the "start_boundary" field.
func (_c *SessionPublishedVersionCreate) SetStartBoundary(v sessionpublishedversion.StartBoundary) *SessionPublishedVersionCreate {
	_c.mutation.SetStartBoundary(v)
	return _c
}

// SetEndBoundary sets the "end_boundary" field.
func (_c *SessionPublishedVersionCreate) SetEndBoundary(v sessionpublishedversion.EndBoundary) *SessionPublishedVersionCreate {
	_c.mutation.SetEndBoundary(v)
	return _c
}

// SetSubmissionDeadline sets the "submission_deadline" field.
func (_c *SessionPublishedVersionCreate) SetSubmissionDeadline(v time.Time) *SessionPublishedVersionCreate {
	_c.mutation.SetSubmissionDeadline(v)
	return _c
}

// SetNillableSubmissionDeadline sets the "submission_deadline" field if the given value is not nil.
func (_c *SessionPublishedVersionCreate) SetNillableSubmissionDeadline(v *time.Time) *SessionPublishedVersionCreate {
	if v != nil {
		_c.SetSubmissionDeadline(*v)
	}
	return _c
}

// SetEntryDefaultDisposition sets the "entry_default_disposition" field.
func (_c *SessionPublishedVersionCreate) SetEntryDefaultDisposition(v sessionpublishedversion.EntryDefaultDisposition) *SessionPublishedVersionCreate {
	_c.mutation.SetEntryDefaultDisposition(v)
	return _c
}

// SetNillableEntryDefaultDisposition sets the "entry_default_disposition" field if the given value is not nil.
func (_c *SessionPublishedVersionCreate) SetNillableEntryDefaultDisposition(v *sessionpublishedversion.EntryDefaultDisposition) *SessionPublishedVersionCreate {
	if v != nil {
		_c.SetEntryDefaultDisposition(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SessionPublishedVersionCreate) SetCreatedAt(v time.Time) *SessionPublishedVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SessionPublishedVersionCreate) SetNillableCreatedAt(v *time.Time) *SessionPublishedVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSession sets the "session" edge to the Session entity.
func (_c *SessionPublishedVersionCreate) SetSession(v *Session) *SessionPublishedVersionCreate {
	return _c.SetSessionID(v.ID)
}

// AddLaneIDs adds the "lanes" edge to the Lane entity by IDs.
func (_c *SessionPublishedVersionCreate) AddLaneIDs(ids ...int) *SessionPublishedVersionCreate {
	_c.mutation.AddLaneIDs(ids...)
	return _c
}

// AddLanes adds the "lanes" edges to the Lane entity.
func (_c *SessionPublishedVersionCreate) AddLanes(v ...*Lane) *SessionPublishedVersionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLaneIDs(ids...)
}

// AddLocationIDs adds the "locations" edge to the Location entity by IDs.
func (_c *SessionPublishedVersionCreate) AddLocationIDs(ids ...int) *SessionPublishedVersionCreate {
	_c.mutation.AddLocationIDs(ids...)
	return _c
}

// AddLocations adds the "locations" edges to the Location entity.
func (_c *SessionPublishedVersionCreate) AddLocations(v ...*Location) *SessionPublishedVersionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLocationIDs(ids...)
}

// AddTrackIDs adds the "tracks" edge to the Track entity by IDs.
func (_c *SessionPublishedVersionCreate) AddTrackIDs(ids ...int) *SessionPublishedVersionCreate {
	_c.mutation.AddTrackIDs(ids...)
	return _c
}

// AddTracks adds the "tracks" edges to the Track entity.
func (_c *SessionPublishedVersionCreate) AddTracks(v ...*Track) *SessionPublishedVersionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTrackIDs(ids...)
}

// Mutation returns the SessionPublishedVersionMutation object of the builder.
func (_c *SessionPublishedVersionCreate) Mutation() *SessionPublishedVersionMutation {
	return _c.mutation
}

// Save creates the SessionPublishedVersion in the database.
func (_c *SessionPublishedVersionCreate) Save(ctx context.Context) (*SessionPublishedVersion, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionPublishedVersionCreate) SaveX(ctx context.Context) *SessionPublishedVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionPublishedVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionPublishedVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionPublishedVersionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sessionpublishedversion.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sessionpublishedversion.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sessionpublishedversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionPublishedVersionCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "SessionPublishedVersion.session_id"`)}
	}
	if _, ok := _c.mutation.PublishedRevision(); !ok {
		return &ValidationError{Name: "published_revision", err: errors.New(`ent: missing required field "SessionPublishedVersion.published_revision"`)}
	}
	if v, ok := _c.mutation.PublishedRevision(); ok {
		if err := sessionpublishedversion.PublishedRevisionValidator(v); err != nil {
			return &ValidationError{Name: "published_revision", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.published_revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "SessionPublishedVersion.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := sessionpublishedversion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Speaker(); ok {
		if err := sessionpublishedversion.SpeakerValidator(v); err != nil {
			return &ValidationError{Name: "speaker", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.speaker": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SessionPublishedVersion.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := sessionpublishedversion.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AudienceVisibility(); !ok {
		return &ValidationError{Name: "audience_visibility", err: errors.New(`ent: missing required field "SessionPublishedVersion.audience_visibility"`)}
	}
	if v, ok := _c.mutation.AudienceVisibility(); ok {
		if err := sessionpublishedversion.AudienceVisibilityValidator(v); err != nil {
			return &ValidationError{Name: "audience_visibility", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.audience_visibility": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PublicDetails(); ok {
		if err := sessionpublishedversion.PublicDetailsValidator(v); err != nil {
			return &ValidationError{Name: "public_details", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.public_details": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CrewNotes(); ok {
		if err := sessionpublishedversion.CrewNotesValidator(v); err != nil {
			return &ValidationError{Name: "crew_notes", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.crew_notes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlannedStart(); !ok {
		return &ValidationError{Name: "planned_start", err: errors.New(`ent: missing required field "SessionPublishedVersion.planned_start"`)}
	}
	if _, ok := _c.mutation.PlannedEnd(); !ok {
		return &ValidationError{Name: "planned_end", err: errors.New(`ent: missing required field "SessionPublishedVersion.planned_end"`)}
	}
	if _, ok := _c.mutation.TimingPolicy(); !ok {
		return &ValidationError{Name: "timing_policy", err: errors.New(`ent: missing required field "SessionPublishedVersion.timing_policy"`)}
	}
	if v, ok := _c.mutation.TimingPolicy(); ok {
		if err := sessionpublishedversion.TimingPolicyValidator(v); err != nil {
			return &ValidationError{Name: "timing_policy", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.timing_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MinimumDurationSeconds(); !ok {
		return &ValidationError{Name: "minimum_duration_seconds", err: errors.New(`ent: missing required field "SessionPublishedVersion.minimum_duration_seconds"`)}
	}
	if v, ok := _c.mutation.MinimumDurationSeconds(); ok {
		if err := sessionpublishedversion.MinimumDurationSecondsValidator(v); err != nil {
			return &ValidationError{Name: "minimum_duration_seconds", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.minimum_duration_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartBoundary(); !ok {
		return &ValidationError{Name: "start_boundary", err: errors.New(`ent: missing required field "SessionPublishedVersion.start_boundary"`)}
	}
	if v, ok := _c.mutation.StartBoundary(); ok {
		if err := sessionpublishedversion.StartBoundaryValidator(v); err != nil {
			return &ValidationError{Name: "start_boundary", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.start_boundary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EndBoundary(); !ok {
		return &ValidationError{Name: "end_boundary", err: errors.New(`ent: missing required field "SessionPublishedVersion.end_boundary"`)}
	}
	if v, ok := _c.mutation.EndBoundary(); ok {
		if err := sessionpublishedversion.EndBoundaryValidator(v); err != nil {
			return &ValidationError{Name: "end_boundary", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.end_boundary": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EntryDefaultDisposition(); ok {
		if err := sessionpublishedversion.EntryDefaultDispositionValidator(v); err != nil {
			return &ValidationError{Name: "entry_default_disposition", err: fmt.Errorf(`ent: validator failed for field "SessionPublishedVersion.entry_default_disposition": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SessionPublishedVersion.created_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "SessionPublishedVersion.session"`)}
	}
	return nil
}

func (_c *SessionPublishedVersionCreate) sqlSave(ctx context.Context) (*SessionPublishedVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionPublishedVersionCreate) createSpec() (*SessionPublishedVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &SessionPublishedVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sessionpublishedversion.Table, sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PublishedRevision(); ok {
		_spec.SetField(sessionpublishedversion.FieldPublishedRevision, field.TypeInt, value)
		_node.PublishedRevision = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(sessionpublishedversion.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Speaker(); ok {
		_spec.SetField(sessionpublishedversion.FieldSpeaker, field.TypeString, value)
		_node.Speaker = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(sessionpublishedversion.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.AudienceVisibility(); ok {
		_spec.SetField(sessionpublishedversion.FieldAudienceVisibility, field.TypeEnum, value)
		_node.AudienceVisibility = value
	}
	if value, ok := _c.mutation.PublicDetails(); ok {
		_spec.SetField(sessionpublishedversion.FieldPublicDetails, field.TypeString, value)
		_node.PublicDetails = value
	}
	if value, ok := _c.mutation.CrewNotes(); ok {
		_spec.SetField(sessionpublishedversion.FieldCrewNotes, field.TypeString, value)
		_node.CrewNotes = value
	}
	if value, ok := _c.mutation.PlannedStart(); ok {
		_spec.SetField(sessionpublishedversion.FieldPlannedStart, field.TypeTime, value)
		_node.PlannedStart = value
	}
	if value, ok := _c.mutation.PlannedEnd(); ok {
		_spec.SetField(sessionpublishedversion.FieldPlannedEnd, field.TypeTime, value)
		_node.PlannedEnd = value
	}
	if value, ok := _c.mutation.TimingPolicy(); ok {
		_spec.SetField(sessionpublishedversion.FieldTimingPolicy, field.TypeEnum, value)
		_node.TimingPolicy = value
	}
	if value, ok := _c.mutation.MinimumDurationSeconds(); ok {
		_spec.SetField(sessionpublishedversion.FieldMinimumDurationSeconds, field.TypeInt, value)
		_node.MinimumDurationSeconds = value
	}
	if value, ok := _c.mutation.StartBoundary(); ok {
		_spec.SetField(sessionpublishedversion.FieldStartBoundary, field.TypeEnum, value)
		_node.StartBoundary = value
	}
	if value, ok := _c.mutation.EndBoundary(); ok {
		_spec.SetField(sessionpublishedversion.FieldEndBoundary, field.TypeEnum, value)
		_node.EndBoundary = value
	}
	if value, ok := _c.mutation.SubmissionDeadline(); ok {
		_spec.SetField(sessionpublishedversion.FieldSubmissionDeadline, field.TypeTime, value)
		_node.SubmissionDeadline = value
	}
	if value, ok := _c.mutation.EntryDefaultDisposition(); ok {
		_spec.SetField(sessionpublishedversion.FieldEntryDefaultDisposition, field.TypeEnum, value)
		_node.EntryDefaultDisposition = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sessionpublishedversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionpublishedversion.SessionTable,
			Columns: []string{sessionpublishedversion.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LanesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sessionpublishedversion.LanesTable,
			Columns: sessionpublishedversion.LanesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lane.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sessionpublishedversion.LocationsTable,
			Columns: sessionpublishedversion.LocationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TracksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sessionpublishedversion.TracksTable,
			Columns: sessionpublishedversion.TracksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SessionPublishedVersionCreateBulk is the builder for creating many SessionPublishedVersion entities in bulk.
type SessionPublishedVersionCreateBulk struct {
	config
	err      error
	builders []*SessionPublishedVersionCreate
}

// Save creates the SessionPublishedVersion entities in the database.
func (_c *SessionPublishedVersionCreateBulk) Save(ctx context.Context) ([]*SessionPublishedVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SessionPublishedVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionPublishedVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionPublishedVersionCreateBulk) SaveX(ctx context.Context) []*SessionPublishedVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionPublishedVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionPublishedVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
