// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/predicate"
	"github.com/dotwaffle/beamers/ent/sessionrun"
	"github.com/dotwaffle/beamers/ent/sessionrunamendment"
)

// SessionRunAmendmentQuery is the builder for querying SessionRunAmendment entities.
type SessionRunAmendmentQuery struct {
	config
	ctx            *QueryContext
	order          []sessionrunamendment.OrderOption
	inters         []Interceptor
	predicates     []predicate.SessionRunAmendment
	withSessionRun *SessionRunQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SessionRunAmendmentQuery builder.
func (_q *SessionRunAmendmentQuery) Where(ps ...predicate.SessionRunAmendment) *SessionRunAmendmentQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SessionRunAmendmentQuery) Limit(limit int) *SessionRunAmendmentQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SessionRunAmendmentQuery) Offset(offset int) *SessionRunAmendmentQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SessionRunAmendmentQuery) Unique(unique bool) *SessionRunAmendmentQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SessionRunAmendmentQuery) Order(o ...sessionrunamendment.OrderOption) *SessionRunAmendmentQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySessionRun chains the current query on the "session_run" edge.
func (_q *SessionRunAmendmentQuery) QuerySessionRun() *SessionRunQuery {
	query := (&SessionRunClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sessionrunamendment.Table, sessionrunamendment.FieldID, selector),
			sqlgraph.To(sessionrun.Table, sessionrun.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sessionrunamendment.SessionRunTable, sessionrunamendment.SessionRunColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SessionRunAmendment entity from the query.
// Returns a *NotFoundError when no SessionRunAmendment was found.
func (_q *SessionRunAmendmentQuery) First(ctx context.Context) (*SessionRunAmendment, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sessionrunamendment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SessionRunAmendmentQuery) FirstX(ctx context.Context) *SessionRunAmendment {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SessionRunAmendment ID from the query.
// Returns a *NotFoundError when no SessionRunAmendment ID was found.
func (_q *SessionRunAmendmentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sessionrunamendment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SessionRunAmendmentQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SessionRunAmendment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SessionRunAmendment entity is found.
// Returns a *NotFoundError when no SessionRunAmendment entities are found.
func (_q *SessionRunAmendmentQuery) Only(ctx context.Context) (*SessionRunAmendment, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sessionrunamendment.Label}
	default:
		return nil, &NotSingularError{sessionrunamendment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SessionRunAmendmentQuery) OnlyX(ctx context.Context) *SessionRunAmendment {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SessionRunAmendment ID in the query.
// Returns a *NotSingularError when more than one SessionRunAmendment ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SessionRunAmendmentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sessionrunamendment.Label}
	default:
		err = &NotSingularError{sessionrunamendment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SessionRunAmendmentQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SessionRunAmendments.
func (_q *SessionRunAmendmentQuery) All(ctx context.Context) ([]*SessionRunAmendment, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SessionRunAmendment, *SessionRunAmendmentQuery]()
	return withInterceptors[[]*SessionRunAmendment](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SessionRunAmendmentQuery) AllX(ctx context.Context) []*SessionRunAmendment {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SessionRunAmendment IDs.
func (_q *SessionRunAmendmentQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(sessionrunamendment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SessionRunAmendmentQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SessionRunAmendmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SessionRunAmendmentQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SessionRunAmendmentQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SessionRunAmendmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SessionRunAmendmentQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SessionRunAmendmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SessionRunAmendmentQuery) Clone() *SessionRunAmendmentQuery {
	if _q == nil {
		return nil
	}
	return &SessionRunAmendmentQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]sessionrunamendment.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.SessionRunAmendment{}, _q.predicates...),
		withSessionRun: _q.withSessionRun.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSessionRun tells the query-builder to eager-load the nodes that are connected to
// the "session_run" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SessionRunAmendmentQuery) WithSessionRun(opts ...func(*SessionRunQuery)) *SessionRunAmendmentQuery {
	query := (&SessionRunClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSessionRun = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SessionRunID int `json:"session_run_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SessionRunAmendment.Query().
//		GroupBy(sessionrunamendment.FieldSessionRunID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SessionRunAmendmentQuery) GroupBy(field string, fields ...string) *SessionRunAmendmentGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SessionRunAmendmentGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = sessionrunamendment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SessionRunID int `json:"session_run_id,omitempty"`
//	}
//
//	client.SessionRunAmendment.Query().
//		Select(sessionrunamendment.FieldSessionRunID).
//		Scan(ctx, &v)
func (_q *SessionRunAmendmentQuery) Select(fields ...string) *SessionRunAmendmentSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SessionRunAmendmentSelect{SessionRunAmendmentQuery: _q}
	sbuild.label = sessionrunamendment.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SessionRunAmendmentSelect configured with the given aggregations.
func (_q *SessionRunAmendmentQuery) Aggregate(fns ...AggregateFunc) *SessionRunAmendmentSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SessionRunAmendmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !sessionrunamendment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if sessionrunamendment.Policy == nil {
		return errors.New("ent: uninitialized sessionrunamendment.Policy (forgotten import ent/runtime?)")
	}
	if err := sessionrunamendment.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *SessionRunAmendmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SessionRunAmendment, error) {
	var (
		nodes       = []*SessionRunAmendment{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withSessionRun != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SessionRunAmendment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SessionRunAmendment{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSessionRun; query != nil {
		if err := _q.loadSessionRun(ctx, query, nodes, nil,
			func(n *SessionRunAmendment, e *SessionRun) { n.Edges.SessionRun = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SessionRunAmendmentQuery) loadSessionRun(ctx context.Context, query *SessionRunQuery, nodes []*SessionRunAmendment, init func(*SessionRunAmendment), assign func(*SessionRunAmendment, *SessionRun)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SessionRunAmendment)
	for i := range nodes {
		fk := nodes[i].SessionRunID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sessionrun.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "session_run_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SessionRunAmendmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SessionRunAmendmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sessionrunamendment.Table, sessionrunamendment.Columns, sqlgraph.NewFieldSpec(sessionrunamendment.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sessionrunamendment.FieldID)
		for i := range fields {
			if fields[i] != sessionrunamendment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSessionRun != nil {
			_spec.Node.AddColumnOnce(sessionrunamendment.FieldSessionRunID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SessionRunAmendmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(sessionrunamendment.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = sessionrunamendment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SessionRunAmendmentGroupBy is the group-by builder for SessionRunAmendment entities.
type SessionRunAmendmentGroupBy struct {
	selector
	build *SessionRunAmendmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SessionRunAmendmentGroupBy) Aggregate(fns ...AggregateFunc) *SessionRunAmendmentGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SessionRunAmendmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SessionRunAmendmentQuery, *SessionRunAmendmentGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SessionRunAmendmentGroupBy) sqlScan(ctx context.Context, root *SessionRunAmendmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SessionRunAmendmentSelect is the builder for selecting fields of SessionRunAmendment entities.
type SessionRunAmendmentSelect struct {
	*SessionRunAmendmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SessionRunAmendmentSelect) Aggregate(fns ...AggregateFunc) *SessionRunAmendmentSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SessionRunAmendmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SessionRunAmendmentQuery, *SessionRunAmendmentSelect](ctx, _s.SessionRunAmendmentQuery, _s, _s.inters, v)
}

func (_s *SessionRunAmendmentSelect) sqlScan(ctx context.Context, root *SessionRunAmendmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
