// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/predicate"
	"github.com/dotwaffle/beamers/ent/session"
	"github.com/dotwaffle/beamers/ent/sessioncancellation"
	"github.com/dotwaffle/beamers/ent/sessiondraft"
	"github.com/dotwaffle/beamers/ent/sessionpublishedversion"
	"github.com/dotwaffle/beamers/ent/sessionrun"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLifecycle sets the "lifecycle" field.
func (_u *SessionUpdate) SetLifecycle(v session.Lifecycle) *SessionUpdate {
	_u.mutation.SetLifecycle(v)
	return _u
}

// SetNillableLifecycle sets the "lifecycle" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLifecycle(v *session.Lifecycle) *SessionUpdate {
	if v != nil {
		_u.SetLifecycle(*v)
	}
	return _u
}

// SetLiveStateRevision sets the "live_state_revision" field.
func (_u *SessionUpdate) SetLiveStateRevision(v int) *SessionUpdate {
	_u.mutation.ResetLiveStateRevision()
	_u.mutation.SetLiveStateRevision(v)
	return _u
}

// SetNillableLiveStateRevision sets the "live_state_revision" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLiveStateRevision(v *int) *SessionUpdate {
	if v != nil {
		_u.SetLiveStateRevision(*v)
	}
	return _u
}

// AddLiveStateRevision adds value to the "live_state_revision" field.
func (_u *SessionUpdate) AddLiveStateRevision(v int) *SessionUpdate {
	_u.mutation.AddLiveStateRevision(v)
	return _u
}

// SetForecastStart sets the "forecast_start" field.
func (_u *SessionUpdate) SetForecastStart(v time.Time) *SessionUpdate {
	_u.mutation.SetForecastStart(v)
	return _u
}

// SetNillableForecastStart sets the "forecast_start" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableForecastStart(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetForecastStart(*v)
	}
	return _u
}

// ClearForecastStart clears the value of the "forecast_start" field.
func (_u *SessionUpdate) ClearForecastStart() *SessionUpdate {
	_u.mutation.ClearForecastStart()
	return _u
}

// SetForecastEnd sets the "forecast_end" field.
func (_u *SessionUpdate) SetForecastEnd(v time.Time) *SessionUpdate {
	_u.mutation.SetForecastEnd(v)
	return _u
}

// SetNillableForecastEnd sets the "forecast_end" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableForecastEnd(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetForecastEnd(*v)
	}
	return _u
}

// ClearForecastEnd clears the value of the "forecast_end" field.
func (_u *SessionUpdate) ClearForecastEnd() *SessionUpdate {
	_u.mutation.ClearForecastEnd()
	return _u
}

// SetPreviousForecastStart sets the "previous_forecast_start" field.
func (_u *SessionUpdate) SetPreviousForecastStart(v time.Time) *SessionUpdate {
	_u.mutation.SetPreviousForecastStart(v)
	return _u
}

// SetNillablePreviousForecastStart sets the "previous_forecast_start" field if the given value is not nil.
func (_u *SessionUpdate) SetNillablePreviousForecastStart(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetPreviousForecastStart(*v)
	}
	return _u
}

// ClearPreviousForecastStart clears the value of the "previous_forecast_start" field.
func (_u *SessionUpdate) ClearPreviousForecastStart() *SessionUpdate {
	_u.mutation.ClearPreviousForecastStart()
	return _u
}

// SetForecastLaneIds sets the "forecast_lane_ids" field.
func (_u *SessionUpdate) SetForecastLaneIds(v []int) *SessionUpdate {
	_u.mutation.SetForecastLaneIds(v)
	return _u
}

// AppendForecastLaneIds appends value to the "forecast_lane_ids" field.
func (_u *SessionUpdate) AppendForecastLaneIds(v []int) *SessionUpdate {
	_u.mutation.AppendForecastLaneIds(v)
	return _u
}

// ClearForecastLaneIds clears the value of the "forecast_lane_ids" field.
func (_u *SessionUpdate) ClearForecastLaneIds() *SessionUpdate {
	_u.mutation.ClearForecastLaneIds()
	return _u
}

// SetForecastLocationIds sets the "forecast_location_ids" field.
func (_u *SessionUpdate) SetForecastLocationIds(v []int) *SessionUpdate {
	_u.mutation.SetForecastLocationIds(v)
	return _u
}

// AppendForecastLocationIds appends value to the "forecast_location_ids" field.
func (_u *SessionUpdate) AppendForecastLocationIds(v []int) *SessionUpdate {
	_u.mutation.AppendForecastLocationIds(v)
	return _u
}

// ClearForecastLocationIds clears the value of the "forecast_location_ids" field.
func (_u *SessionUpdate) ClearForecastLocationIds() *SessionUpdate {
	_u.mutation.ClearForecastLocationIds()
	return _u
}

// SetPublicCancellationMessage sets the "public_cancellation_message" field.
func (_u *SessionUpdate) SetPublicCancellationMessage(v string) *SessionUpdate {
	_u.mutation.SetPublicCancellationMessage(v)
	return _u
}

// SetNillablePublicCancellationMessage sets the "public_cancellation_message" field if the given value is not nil.
func (_u *SessionUpdate) SetNillablePublicCancellationMessage(v *string) *SessionUpdate {
	if v != nil {
		_u.SetPublicCancellationMessage(*v)
	}
	return _u
}

// ClearPublicCancellationMessage clears the value of the "public_cancellation_message" field.
func (_u *SessionUpdate) ClearPublicCancellationMessage() *SessionUpdate {
	_u.mutation.ClearPublicCancellationMessage()
	return _u
}

// SetCancellationCrewNotes sets the "cancellation_crew_notes" field.
func (_u *SessionUpdate) SetCancellationCrewNotes(v string) *SessionUpdate {
	_u.mutation.SetCancellationCrewNotes(v)
	return _u
}

// SetNillableCancellationCrewNotes sets the "cancellation_crew_notes" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCancellationCrewNotes(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCancellationCrewNotes(*v)
	}
	return _u
}

// ClearCancellationCrewNotes clears the value of the "cancellation_crew_notes" field.
func (_u *SessionUpdate) ClearCancellationCrewNotes() *SessionUpdate {
	_u.mutation.ClearCancellationCrewNotes()
	return _u
}

// SetCorrectedTitle sets the "corrected_title" field.
func (_u *SessionUpdate) SetCorrectedTitle(v string) *SessionUpdate {
	_u.mutation.SetCorrectedTitle(v)
	return _u
}

// SetNillableCorrectedTitle sets the "corrected_title" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCorrectedTitle(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCorrectedTitle(*v)
	}
	return _u
}

// ClearCorrectedTitle clears the value of the "corrected_title" field.
func (_u *SessionUpdate) ClearCorrectedTitle() *SessionUpdate {
	_u.mutation.ClearCorrectedTitle()
	return _u
}

// SetCorrectedSpeaker sets the "corrected_speaker" field.
func (_u *SessionUpdate) SetCorrectedSpeaker(v string) *SessionUpdate {
	_u.mutation.SetCorrectedSpeaker(v)
	return _u
}

// SetNillableCorrectedSpeaker sets the "corrected_speaker" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCorrectedSpeaker(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCorrectedSpeaker(*v)
	}
	return _u
}

// ClearCorrectedSpeaker clears the value of the "corrected_speaker" field.
func (_u *SessionUpdate) ClearCorrectedSpeaker() *SessionUpdate {
	_u.mutation.ClearCorrectedSpeaker()
	return _u
}

// SetCorrectedPublicDetails sets the "corrected_public_details" field.
func (_u *SessionUpdate) SetCorrectedPublicDetails(v string) *SessionUpdate {
	_u.mutation.SetCorrectedPublicDetails(v)
	return _u
}

// SetNillableCorrectedPublicDetails sets the "corrected_public_details" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCorrectedPublicDetails(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCorrectedPublicDetails(*v)
	}
	return _u
}

// ClearCorrectedPublicDetails clears the value of the "corrected_public_details" field.
func (_u *SessionUpdate) ClearCorrectedPublicDetails() *SessionUpdate {
	_u.mutation.ClearCorrectedPublicDetails()
	return _u
}

// SetDraftID sets the "draft" edge to the SessionDraft entity by ID.
func (_u *SessionUpdate) SetDraftID(id int) *SessionUpdate {
	_u.mutation.SetDraftID(id)
	return _u
}

// SetNillableDraftID sets the "draft" edge to the SessionDraft entity by ID if the given value is not nil.
func (_u *SessionUpdate) SetNillableDraftID(id *int) *SessionUpdate {
	if id != nil {
		_u = _u.SetDraftID(*id)
	}
	return _u
}

// SetDraft sets the "draft" edge to the SessionDraft entity.
func (_u *SessionUpdate) SetDraft(v *SessionDraft) *SessionUpdate {
	return _u.SetDraftID(v.ID)
}

// AddPublishedVersionIDs adds the "published_versions" edge to the SessionPublishedVersion entity by IDs.
func (_u *SessionUpdate) AddPublishedVersionIDs(ids ...int) *SessionUpdate {
	_u.mutation.AddPublishedVersionIDs(ids...)
	return _u
}

// AddPublishedVersions adds the "published_versions" edges to the SessionPublishedVersion entity.
func (_u *SessionUpdate) AddPublishedVersions(v ...*SessionPublishedVersion) *SessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublishedVersionIDs(ids...)
}

// AddRunIDs adds the "runs" edge to the SessionRun entity by IDs.
func (_u *SessionUpdate) AddRunIDs(ids ...int) *SessionUpdate {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the SessionRun entity.
func (_u *SessionUpdate) AddRuns(v ...*SessionRun) *SessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// AddCancellationIDs adds the "cancellations" edge to the SessionCancellation entity by IDs.
func (_u *SessionUpdate) AddCancellationIDs(ids ...int) *SessionUpdate {
	_u.mutation.AddCancellationIDs(ids...)
	return _u
}

// AddCancellations adds the "cancellations" edges to the SessionCancellation entity.
func (_u *SessionUpdate) AddCancellations(v ...*SessionCancellation) *SessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCancellationIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearDraft clears the "draft" edge to the SessionDraft entity.
func (_u *SessionUpdate) ClearDraft() *SessionUpdate {
	_u.mutation.ClearDraft()
	return _u
}

// ClearPublishedVersions clears all "published_versions" edges to the SessionPublishedVersion entity.
func (_u *SessionUpdate) ClearPublishedVersions() *SessionUpdate {
	_u.mutation.ClearPublishedVersions()
	return _u
}

// RemovePublishedVersionIDs removes the "published_versions" edge to SessionPublishedVersion entities by IDs.
func (_u *SessionUpdate) RemovePublishedVersionIDs(ids ...int) *SessionUpdate {
	_u.mutation.RemovePublishedVersionIDs(ids...)
	return _u
}

// RemovePublishedVersions removes "published_versions" edges to SessionPublishedVersion entities.
func (_u *SessionUpdate) RemovePublishedVersions(v ...*SessionPublishedVersion) *SessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublishedVersionIDs(ids...)
}

// ClearRuns clears all "runs" edges to the SessionRun entity.
func (_u *SessionUpdate) ClearRuns() *SessionUpdate {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to SessionRun entities by IDs.
func (_u *SessionUpdate) RemoveRunIDs(ids ...int) *SessionUpdate {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to SessionRun entities.
func (_u *SessionUpdate) RemoveRuns(v ...*SessionRun) *SessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// ClearCancellations clears all "cancellations" edges to the SessionCancellation entity.
func (_u *SessionUpdate) ClearCancellations() *SessionUpdate {
	_u.mutation.ClearCancellations()
	return _u
}

// RemoveCancellationIDs removes the "cancellations" edge to SessionCancellation entities by IDs.
func (_u *SessionUpdate) RemoveCancellationIDs(ids ...int) *SessionUpdate {
	_u.mutation.RemoveCancellationIDs(ids...)
	return _u
}

// RemoveCancellations removes "cancellations" edges to SessionCancellation entities.
func (_u *SessionUpdate) RemoveCancellations(v ...*SessionCancellation) *SessionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCancellationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdate) check() error {
	if v, ok := _u.mutation.Lifecycle(); ok {
		if err := session.LifecycleValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle", err: fmt.Errorf(`ent: validator failed for field "Session.lifecycle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LiveStateRevision(); ok {
		if err := session.LiveStateRevisionValidator(v); err != nil {
			return &ValidationError{Name: "live_state_revision", err: fmt.Errorf(`ent: validator failed for field "Session.live_state_revision": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicCancellationMessage(); ok {
		if err := session.PublicCancellationMessageValidator(v); err != nil {
			return &ValidationError{Name: "public_cancellation_message", err: fmt.Errorf(`ent: validator failed for field "Session.public_cancellation_message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CancellationCrewNotes(); ok {
		if err := session.CancellationCrewNotesValidator(v); err != nil {
			return &ValidationError{Name: "cancellation_crew_notes", err: fmt.Errorf(`ent: validator failed for field "Session.cancellation_crew_notes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CorrectedTitle(); ok {
		if err := session.CorrectedTitleValidator(v); err != nil {
			return &ValidationError{Name: "corrected_title", err: fmt.Errorf(`ent: validator failed for field "Session.corrected_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CorrectedSpeaker(); ok {
		if err := session.CorrectedSpeakerValidator(v); err != nil {
			return &ValidationError{Name: "corrected_speaker", err: fmt.Errorf(`ent: validator failed for field "Session.corrected_speaker": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CorrectedPublicDetails(); ok {
		if err := session.CorrectedPublicDetailsValidator(v); err != nil {
			return &ValidationError{Name: "corrected_public_details", err: fmt.Errorf(`ent: validator failed for field "Session.corrected_public_details": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.event"`)
	}
	return nil
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Lifecycle(); ok {
		_spec.SetField(session.FieldLifecycle, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LiveStateRevision(); ok {
		_spec.SetField(session.FieldLiveStateRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLiveStateRevision(); ok {
		_spec.AddField(session.FieldLiveStateRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ForecastStart(); ok {
		_spec.SetField(session.FieldForecastStart, field.TypeTime, value)
	}
	if _u.mutation.ForecastStartCleared() {
		_spec.ClearField(session.FieldForecastStart, field.TypeTime)
	}
	if value, ok := _u.mutation.ForecastEnd(); ok {
		_spec.SetField(session.FieldForecastEnd, field.TypeTime, value)
	}
	if _u.mutation.ForecastEndCleared() {
		_spec.ClearField(session.FieldForecastEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.PreviousForecastStart(); ok {
		_spec.SetField(session.FieldPreviousForecastStart, field.TypeTime, value)
	}
	if _u.mutation.PreviousForecastStartCleared() {
		_spec.ClearField(session.FieldPreviousForecastStart, field.TypeTime)
	}
	if value, ok := _u.mutation.ForecastLaneIds(); ok {
		_spec.SetField(session.FieldForecastLaneIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedForecastLaneIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, session.FieldForecastLaneIds, value)
		})
	}
	if _u.mutation.ForecastLaneIdsCleared() {
		_spec.ClearField(session.FieldForecastLaneIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.ForecastLocationIds(); ok {
		_spec.SetField(session.FieldForecastLocationIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedForecastLocationIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, session.FieldForecastLocationIds, value)
		})
	}
	if _u.mutation.ForecastLocationIdsCleared() {
		_spec.ClearField(session.FieldForecastLocationIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublicCancellationMessage(); ok {
		_spec.SetField(session.FieldPublicCancellationMessage, field.TypeString, value)
	}
	if _u.mutation.PublicCancellationMessageCleared() {
		_spec.ClearField(session.FieldPublicCancellationMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CancellationCrewNotes(); ok {
		_spec.SetField(session.FieldCancellationCrewNotes, field.TypeString, value)
	}
	if _u.mutation.CancellationCrewNotesCleared() {
		_spec.ClearField(session.FieldCancellationCrewNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CorrectedTitle(); ok {
		_spec.SetField(session.FieldCorrectedTitle, field.TypeString, value)
	}
	if _u.mutation.CorrectedTitleCleared() {
		_spec.ClearField(session.FieldCorrectedTitle, field.TypeString)
	}
	if value, ok := _u.mutation.CorrectedSpeaker(); ok {
		_spec.SetField(session.FieldCorrectedSpeaker, field.TypeString, value)
	}
	if _u.mutation.CorrectedSpeakerCleared() {
		_spec.ClearField(session.FieldCorrectedSpeaker, field.TypeString)
	}
	if value, ok := _u.mutation.CorrectedPublicDetails(); ok {
		_spec.SetField(session.FieldCorrectedPublicDetails, field.TypeString, value)
	}
	if _u.mutation.CorrectedPublicDetailsCleared() {
		_spec.ClearField(session.FieldCorrectedPublicDetails, field.TypeString)
	}
	if _u.mutation.DraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.DraftTable,
			Columns: []string{session.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.DraftTable,
			Columns: []string{session.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PublishedVersionsTable,
			Columns: []string{session.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PublishedVersionsTable,
			Columns: []string{session.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PublishedVersionsTable,
			Columns: []string{session.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RunsTable,
			Columns: []string{session.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RunsTable,
			Columns: []string{session.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RunsTable,
			Columns: []string{session.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CancellationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.CancellationsTable,
			Columns: []string{session.CancellationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessioncancellation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCancellationsIDs(); len(nodes) > 0 && !_u.mutation.CancellationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.CancellationsTable,
			Columns: []string{session.CancellationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessioncancellation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CancellationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.CancellationsTable,
			Columns: []string{session.CancellationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessioncancellation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetLifecycle sets the "lifecycle" field.
func (_u *SessionUpdateOne) SetLifecycle(v session.Lifecycle) *SessionUpdateOne {
	_u.mutation.SetLifecycle(v)
	return _u
}

// SetNillableLifecycle sets the "lifecycle" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLifecycle(v *session.Lifecycle) *SessionUpdateOne {
	if v != nil {
		_u.SetLifecycle(*v)
	}
	return _u
}

// SetLiveStateRevision sets the "live_state_revision" field.
func (_u *SessionUpdateOne) SetLiveStateRevision(v int) *SessionUpdateOne {
	_u.mutation.ResetLiveStateRevision()
	_u.mutation.SetLiveStateRevision(v)
	return _u
}

// SetNillableLiveStateRevision sets the "live_state_revision" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLiveStateRevision(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetLiveStateRevision(*v)
	}
	return _u
}

// AddLiveStateRevision adds value to the "live_state_revision" field.
func (_u *SessionUpdateOne) AddLiveStateRevision(v int) *SessionUpdateOne {
	_u.mutation.AddLiveStateRevision(v)
	return _u
}

// SetForecastStart sets the "forecast_start" field.
func (_u *SessionUpdateOne) SetForecastStart(v time.Time) *SessionUpdateOne {
	_u.mutation.SetForecastStart(v)
	return _u
}

// SetNillableForecastStart sets the "forecast_start" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableForecastStart(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetForecastStart(*v)
	}
	return _u
}

// ClearForecastStart clears the value of the "forecast_start" field.
func (_u *SessionUpdateOne) ClearForecastStart() *SessionUpdateOne {
	_u.mutation.ClearForecastStart()
	return _u
}

// SetForecastEnd sets the "forecast_end" field.
func (_u *SessionUpdateOne) SetForecastEnd(v time.Time) *SessionUpdateOne {
	_u.mutation.SetForecastEnd(v)
	return _u
}

// SetNillableForecastEnd sets the "forecast_end" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableForecastEnd(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetForecastEnd(*v)
	}
	return _u
}

// ClearForecastEnd clears the value of the "forecast_end" field.
func (_u *SessionUpdateOne) ClearForecastEnd() *SessionUpdateOne {
	_u.mutation.ClearForecastEnd()
	return _u
}

// SetPreviousForecastStart sets the "previous_forecast_start" field.
func (_u *SessionUpdateOne) SetPreviousForecastStart(v time.Time) *SessionUpdateOne {
	_u.mutation.SetPreviousForecastStart(v)
	return _u
}

// SetNillablePreviousForecastStart sets the "previous_forecast_start" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillablePreviousForecastStart(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetPreviousForecastStart(*v)
	}
	return _u
}

// ClearPreviousForecastStart clears the value of the "previous_forecast_start" field.
func (_u *SessionUpdateOne) ClearPreviousForecastStart() *SessionUpdateOne {
	_u.mutation.ClearPreviousForecastStart()
	return _u
}

// SetForecastLaneIds sets the "forecast_lane_ids" field.
func (_u *SessionUpdateOne) SetForecastLaneIds(v []int) *SessionUpdateOne {
	_u.mutation.SetForecastLaneIds(v)
	return _u
}

// AppendForecastLaneIds appends value to the "forecast_lane_ids" field.
func (_u *SessionUpdateOne) AppendForecastLaneIds(v []int) *SessionUpdateOne {
	_u.mutation.AppendForecastLaneIds(v)
	return _u
}

// ClearForecastLaneIds clears the value of the "forecast_lane_ids" field.
func (_u *SessionUpdateOne) ClearForecastLaneIds() *SessionUpdateOne {
	_u.mutation.ClearForecastLaneIds()
	return _u
}

// SetForecastLocationIds sets the "forecast_location_ids" field.
func (_u *SessionUpdateOne) SetForecastLocationIds(v []int) *SessionUpdateOne {
	_u.mutation.SetForecastLocationIds(v)
	return _u
}

// AppendForecastLocationIds appends value to the "forecast_location_ids" field.
func (_u *SessionUpdateOne) AppendForecastLocationIds(v []int) *SessionUpdateOne {
	_u.mutation.AppendForecastLocationIds(v)
	return _u
}

// ClearForecastLocationIds clears the value of the "forecast_location_ids" field.
func (_u *SessionUpdateOne) ClearForecastLocationIds() *SessionUpdateOne {
	_u.mutation.ClearForecastLocationIds()
	return _u
}

// SetPublicCancellationMessage sets the "public_cancellation_message" field.
func (_u *SessionUpdateOne) SetPublicCancellationMessage(v string) *SessionUpdateOne {
	_u.mutation.SetPublicCancellationMessage(v)
	return _u
}

// SetNillablePublicCancellationMessage sets the "public_cancellation_message" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillablePublicCancellationMessage(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetPublicCancellationMessage(*v)
	}
	return _u
}

// ClearPublicCancellationMessage clears the value of the "public_cancellation_message" field.
func (_u *SessionUpdateOne) ClearPublicCancellationMessage() *SessionUpdateOne {
	_u.mutation.ClearPublicCancellationMessage()
	return _u
}

// SetCancellationCrewNotes sets the "cancellation_crew_notes" field.
func (_u *SessionUpdateOne) SetCancellationCrewNotes(v string) *SessionUpdateOne {
	_u.mutation.SetCancellationCrewNotes(v)
	return _u
}

// SetNillableCancellationCrewNotes sets the "cancellation_crew_notes" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCancellationCrewNotes(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCancellationCrewNotes(*v)
	}
	return _u
}

// ClearCancellationCrewNotes clears the value of the "cancellation_crew_notes" field.
func (_u *SessionUpdateOne) ClearCancellationCrewNotes() *SessionUpdateOne {
	_u.mutation.ClearCancellationCrewNotes()
	return _u
}

// SetCorrectedTitle sets the "corrected_title" field.
func (_u *SessionUpdateOne) SetCorrectedTitle(v string) *SessionUpdateOne {
	_u.mutation.SetCorrectedTitle(v)
	return _u
}

// SetNillableCorrectedTitle sets the "corrected_title" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCorrectedTitle(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCorrectedTitle(*v)
	}
	return _u
}

// ClearCorrectedTitle clears the value of the "corrected_title" field.
func (_u *SessionUpdateOne) ClearCorrectedTitle() *SessionUpdateOne {
	_u.mutation.ClearCorrectedTitle()
	return _u
}

// SetCorrectedSpeaker sets the "corrected_speaker" field.
func (_u *SessionUpdateOne) SetCorrectedSpeaker(v string) *SessionUpdateOne {
	_u.mutation.SetCorrectedSpeaker(v)
	return _u
}

// SetNillableCorrectedSpeaker sets the "corrected_speaker" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCorrectedSpeaker(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCorrectedSpeaker(*v)
	}
	return _u
}

// ClearCorrectedSpeaker clears the value of the "corrected_speaker" field.
func (_u *SessionUpdateOne) ClearCorrectedSpeaker() *SessionUpdateOne {
	_u.mutation.ClearCorrectedSpeaker()
	return _u
}

// SetCorrectedPublicDetails sets the "corrected_public_details" field.
func (_u *SessionUpdateOne) SetCorrectedPublicDetails(v string) *SessionUpdateOne {
	_u.mutation.SetCorrectedPublicDetails(v)
	return _u
}

// SetNillableCorrectedPublicDetails sets the "corrected_public_details" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCorrectedPublicDetails(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCorrectedPublicDetails(*v)
	}
	return _u
}

// ClearCorrectedPublicDetails clears the value of the "corrected_public_details" field.
func (_u *SessionUpdateOne) ClearCorrectedPublicDetails() *SessionUpdateOne {
	_u.mutation.ClearCorrectedPublicDetails()
	return _u
}

// SetDraftID sets the "draft" edge to the SessionDraft entity by ID.
func (_u *SessionUpdateOne) SetDraftID(id int) *SessionUpdateOne {
	_u.mutation.SetDraftID(id)
	return _u
}

// SetNillableDraftID sets the "draft" edge to the SessionDraft entity by ID if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableDraftID(id *int) *SessionUpdateOne {
	if id != nil {
		_u = _u.SetDraftID(*id)
	}
	return _u
}

// SetDraft sets the "draft" edge to the SessionDraft entity.
func (_u *SessionUpdateOne) SetDraft(v *SessionDraft) *SessionUpdateOne {
	return _u.SetDraftID(v.ID)
}

// AddPublishedVersionIDs adds the "published_versions" edge to the SessionPublishedVersion entity by IDs.
func (_u *SessionUpdateOne) AddPublishedVersionIDs(ids ...int) *SessionUpdateOne {
	_u.mutation.AddPublishedVersionIDs(ids...)
	return _u
}

// AddPublishedVersions adds the "published_versions" edges to the SessionPublishedVersion entity.
func (_u *SessionUpdateOne) AddPublishedVersions(v ...*SessionPublishedVersion) *SessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublishedVersionIDs(ids...)
}

// AddRunIDs adds the "runs" edge to the SessionRun entity by IDs.
func (_u *SessionUpdateOne) AddRunIDs(ids ...int) *SessionUpdateOne {
	_u.mutation.AddRunIDs(ids...)
	return _u
}

// AddRuns adds the "runs" edges to the SessionRun entity.
func (_u *SessionUpdateOne) AddRuns(v ...*SessionRun) *SessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRunIDs(ids...)
}

// AddCancellationIDs adds the "cancellations" edge to the SessionCancellation entity by IDs.
func (_u *SessionUpdateOne) AddCancellationIDs(ids ...int) *SessionUpdateOne {
	_u.mutation.AddCancellationIDs(ids...)
	return _u
}

// AddCancellations adds the "cancellations" edges to the SessionCancellation entity.
func (_u *SessionUpdateOne) AddCancellations(v ...*SessionCancellation) *SessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCancellationIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearDraft clears the "draft" edge to the SessionDraft entity.
func (_u *SessionUpdateOne) ClearDraft() *SessionUpdateOne {
	_u.mutation.ClearDraft()
	return _u
}

// ClearPublishedVersions clears all "published_versions" edges to the SessionPublishedVersion entity.
func (_u *SessionUpdateOne) ClearPublishedVersions() *SessionUpdateOne {
	_u.mutation.ClearPublishedVersions()
	return _u
}

// RemovePublishedVersionIDs removes the "published_versions" edge to SessionPublishedVersion entities by IDs.
func (_u *SessionUpdateOne) RemovePublishedVersionIDs(ids ...int) *SessionUpdateOne {
	_u.mutation.RemovePublishedVersionIDs(ids...)
	return _u
}

// RemovePublishedVersions removes "published_versions" edges to SessionPublishedVersion entities.
func (_u *SessionUpdateOne) RemovePublishedVersions(v ...*SessionPublishedVersion) *SessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublishedVersionIDs(ids...)
}

// ClearRuns clears all "runs" edges to the SessionRun entity.
func (_u *SessionUpdateOne) ClearRuns() *SessionUpdateOne {
	_u.mutation.ClearRuns()
	return _u
}

// RemoveRunIDs removes the "runs" edge to SessionRun entities by IDs.
func (_u *SessionUpdateOne) RemoveRunIDs(ids ...int) *SessionUpdateOne {
	_u.mutation.RemoveRunIDs(ids...)
	return _u
}

// RemoveRuns removes "runs" edges to SessionRun entities.
func (_u *SessionUpdateOne) RemoveRuns(v ...*SessionRun) *SessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRunIDs(ids...)
}

// ClearCancellations clears all "cancellations" edges to the SessionCancellation entity.
func (_u *SessionUpdateOne) ClearCancellations() *SessionUpdateOne {
	_u.mutation.ClearCancellations()
	return _u
}

// RemoveCancellationIDs removes the "cancellations" edge to SessionCancellation entities by IDs.
func (_u *SessionUpdateOne) RemoveCancellationIDs(ids ...int) *SessionUpdateOne {
	_u.mutation.RemoveCancellationIDs(ids...)
	return _u
}

// RemoveCancellations removes "cancellations" edges to SessionCancellation entities.
func (_u *SessionUpdateOne) RemoveCancellations(v ...*SessionCancellation) *SessionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCancellationIDs(ids...)
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdateOne) check() error {
	if v, ok := _u.mutation.Lifecycle(); ok {
		if err := session.LifecycleValidator(v); err != nil {
			return &ValidationError{Name: "lifecycle", err: fmt.Errorf(`ent: validator failed for field "Session.lifecycle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LiveStateRevision(); ok {
		if err := session.LiveStateRevisionValidator(v); err != nil {
			return &ValidationError{Name: "live_state_revision", err: fmt.Errorf(`ent: validator failed for field "Session.live_state_revision": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicCancellationMessage(); ok {
		if err := session.PublicCancellationMessageValidator(v); err != nil {
			return &ValidationError{Name: "public_cancellation_message", err: fmt.Errorf(`ent: validator failed for field "Session.public_cancellation_message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CancellationCrewNotes(); ok {
		if err := session.CancellationCrewNotesValidator(v); err != nil {
			return &ValidationError{Name: "cancellation_crew_notes", err: fmt.Errorf(`ent: validator failed for field "Session.cancellation_crew_notes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CorrectedTitle(); ok {
		if err := session.CorrectedTitleValidator(v); err != nil {
			return &ValidationError{Name: "corrected_title", err: fmt.Errorf(`ent: validator failed for field "Session.corrected_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CorrectedSpeaker(); ok {
		if err := session.CorrectedSpeakerValidator(v); err != nil {
			return &ValidationError{Name: "corrected_speaker", err: fmt.Errorf(`ent: validator failed for field "Session.corrected_speaker": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CorrectedPublicDetails(); ok {
		if err := session.CorrectedPublicDetailsValidator(v); err != nil {
			return &ValidationError{Name: "corrected_public_details", err: fmt.Errorf(`ent: validator failed for field "Session.corrected_public_details": %w`, err)}
		}
	}
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.event"`)
	}
	return nil
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Lifecycle(); ok {
		_spec.SetField(session.FieldLifecycle, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LiveStateRevision(); ok {
		_spec.SetField(session.FieldLiveStateRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLiveStateRevision(); ok {
		_spec.AddField(session.FieldLiveStateRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ForecastStart(); ok {
		_spec.SetField(session.FieldForecastStart, field.TypeTime, value)
	}
	if _u.mutation.ForecastStartCleared() {
		_spec.ClearField(session.FieldForecastStart, field.TypeTime)
	}
	if value, ok := _u.mutation.ForecastEnd(); ok {
		_spec.SetField(session.FieldForecastEnd, field.TypeTime, value)
	}
	if _u.mutation.ForecastEndCleared() {
		_spec.ClearField(session.FieldForecastEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.PreviousForecastStart(); ok {
		_spec.SetField(session.FieldPreviousForecastStart, field.TypeTime, value)
	}
	if _u.mutation.PreviousForecastStartCleared() {
		_spec.ClearField(session.FieldPreviousForecastStart, field.TypeTime)
	}
	if value, ok := _u.mutation.ForecastLaneIds(); ok {
		_spec.SetField(session.FieldForecastLaneIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedForecastLaneIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, session.FieldForecastLaneIds, value)
		})
	}
	if _u.mutation.ForecastLaneIdsCleared() {
		_spec.ClearField(session.FieldForecastLaneIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.ForecastLocationIds(); ok {
		_spec.SetField(session.FieldForecastLocationIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedForecastLocationIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, session.FieldForecastLocationIds, value)
		})
	}
	if _u.mutation.ForecastLocationIdsCleared() {
		_spec.ClearField(session.FieldForecastLocationIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublicCancellationMessage(); ok {
		_spec.SetField(session.FieldPublicCancellationMessage, field.TypeString, value)
	}
	if _u.mutation.PublicCancellationMessageCleared() {
		_spec.ClearField(session.FieldPublicCancellationMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CancellationCrewNotes(); ok {
		_spec.SetField(session.FieldCancellationCrewNotes, field.TypeString, value)
	}
	if _u.mutation.CancellationCrewNotesCleared() {
		_spec.ClearField(session.FieldCancellationCrewNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CorrectedTitle(); ok {
		_spec.SetField(session.FieldCorrectedTitle, field.TypeString, value)
	}
	if _u.mutation.CorrectedTitleCleared() {
		_spec.ClearField(session.FieldCorrectedTitle, field.TypeString)
	}
	if value, ok := _u.mutation.CorrectedSpeaker(); ok {
		_spec.SetField(session.FieldCorrectedSpeaker, field.TypeString, value)
	}
	if _u.mutation.CorrectedSpeakerCleared() {
		_spec.ClearField(session.FieldCorrectedSpeaker, field.TypeString)
	}
	if value, ok := _u.mutation.CorrectedPublicDetails(); ok {
		_spec.SetField(session.FieldCorrectedPublicDetails, field.TypeString, value)
	}
	if _u.mutation.CorrectedPublicDetailsCleared() {
		_spec.ClearField(session.FieldCorrectedPublicDetails, field.TypeString)
	}
	if _u.mutation.DraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.DraftTable,
			Columns: []string{session.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.DraftTable,
			Columns: []string{session.DraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessiondraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PublishedVersionsTable,
			Columns: []string{session.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublishedVersionsIDs(); len(nodes) > 0 && !_u.mutation.PublishedVersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PublishedVersionsTable,
			Columns: []string{session.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedVersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.PublishedVersionsTable,
			Columns: []string{session.PublishedVersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionpublishedversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RunsTable,
			Columns: []string{session.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionrun.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRunsIDs(); len(nodes) > 0 && !_u.mutation.RunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RunsTable,
			Columns: []string{session.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RunsTable,
			Columns: []string{session.RunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CancellationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.CancellationsTable,
			Columns: []string{session.CancellationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessioncancellation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCancellationsIDs(); len(nodes) > 0 && !_u.mutation.CancellationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.CancellationsTable,
			Columns: []string{session.CancellationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessioncancellation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CancellationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.CancellationsTable,
			Columns: []string{session.CancellationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessioncancellation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
