// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/beamers/ent/account"
	"github.com/dotwaffle/beamers/ent/event"
	"github.com/dotwaffle/beamers/ent/votingkey"
)

// VotingKeyCreate is the builder for creating a VotingKey entity.
type VotingKeyCreate struct {
	config
	mutation *VotingKeyMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (_c *VotingKeyCreate) SetEventID(v int) *VotingKeyCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *VotingKeyCreate) SetTokenHash(v string) *VotingKeyCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VotingKeyCreate) SetCreatedAt(v time.Time) *VotingKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VotingKeyCreate) SetNillableCreatedAt(v *time.Time) *VotingKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *VotingKeyCreate) SetExpiresAt(v time.Time) *VotingKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *VotingKeyCreate) SetRevokedAt(v time.Time) *VotingKeyCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *VotingKeyCreate) SetNillableRevokedAt(v *time.Time) *VotingKeyCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetRedeemedAt sets the "redeemed_at" field.
func (_c *VotingKeyCreate) SetRedeemedAt(v time.Time) *VotingKeyCreate {
	_c.mutation.SetRedeemedAt(v)
	return _c
}

// SetNillableRedeemedAt sets the "redeemed_at" field if the given value is not nil.
func (_c *VotingKeyCreate) SetNillableRedeemedAt(v *time.Time) *VotingKeyCreate {
	if v != nil {
		_c.SetRedeemedAt(*v)
	}
	return _c
}

// SetRedeemedByAccountID sets the "redeemed_by_account_id" field.
func (_c *VotingKeyCreate) SetRedeemedByAccountID(v int) *VotingKeyCreate {
	_c.mutation.SetRedeemedByAccountID(v)
	return _c
}

// SetNillableRedeemedByAccountID sets the "redeemed_by_account_id" field if the given value is not nil.
func (_c *VotingKeyCreate) SetNillableRedeemedByAccountID(v *int) *VotingKeyCreate {
	if v != nil {
		_c.SetRedeemedByAccountID(*v)
	}
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *VotingKeyCreate) SetEvent(v *Event) *VotingKeyCreate {
	return _c.SetEventID(v.ID)
}

// SetRedeemedByID sets the "redeemed_by" edge to the Account entity by ID.
func (_c *VotingKeyCreate) SetRedeemedByID(id int) *VotingKeyCreate {
	_c.mutation.SetRedeemedByID(id)
	return _c
}

// SetNillableRedeemedByID sets the "redeemed_by" edge to the Account entity by ID if the given value is not nil.
func (_c *VotingKeyCreate) SetNillableRedeemedByID(id *int) *VotingKeyCreate {
	if id != nil {
		_c = _c.SetRedeemedByID(*id)
	}
	return _c
}

// SetRedeemedBy sets the "redeemed_by" edge to the Account entity.
func (_c *VotingKeyCreate) SetRedeemedBy(v *Account) *VotingKeyCreate {
	return _c.SetRedeemedByID(v.ID)
}

// Mutation returns the VotingKeyMutation object of the builder.
func (_c *VotingKeyCreate) Mutation() *VotingKeyMutation {
	return _c.mutation
}

// Save creates the VotingKey in the database.
func (_c *VotingKeyCreate) Save(ctx context.Context) (*VotingKey, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VotingKeyCreate) SaveX(ctx context.Context) *VotingKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VotingKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VotingKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VotingKeyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if votingkey.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized votingkey.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := votingkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *VotingKeyCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "VotingKey.event_id"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "VotingKey.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := votingkey.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "VotingKey.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VotingKey.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "VotingKey.expires_at"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "VotingKey.event"`)}
	}
	return nil
}

func (_c *VotingKeyCreate) sqlSave(ctx context.Context) (*VotingKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VotingKeyCreate) createSpec() (*VotingKey, *sqlgraph.CreateSpec) {
	var (
		_node = &VotingKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(votingkey.Table, sqlgraph.NewFieldSpec(votingkey.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(votingkey.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(votingkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(votingkey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(votingkey.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.RedeemedAt(); ok {
		_spec.SetField(votingkey.FieldRedeemedAt, field.TypeTime, value)
		_node.RedeemedAt = &value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   votingkey.EventTable,
			Columns: []string{votingkey.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedeemedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   votingkey.RedeemedByTable,
			Columns: []string{votingkey.RedeemedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RedeemedByAccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VotingKeyCreateBulk is the builder for creating many VotingKey entities in bulk.
type VotingKeyCreateBulk struct {
	config
	err      error
	builders []*VotingKeyCreate
}

// Save creates the VotingKey entities in the database.
func (_c *VotingKeyCreateBulk) Save(ctx context.Context) ([]*VotingKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VotingKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VotingKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VotingKeyCreateBulk) SaveX(ctx context.Context) []*VotingKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VotingKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VotingKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
