// Code generated by ent, DO NOT EDIT.

package resultscorrection

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the resultscorrection type in the database.
	Label = "results_correction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldScopeSessionID holds the string denoting the scope_session_id field in the database.
	FieldScopeSessionID = "scope_session_id"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldBasePublicationRevision holds the string denoting the base_publication_revision field in the database.
	FieldBasePublicationRevision = "base_publication_revision"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPublicationOrder holds the string denoting the publication_order field in the database.
	FieldPublicationOrder = "publication_order"
	// FieldItemsJSON holds the string denoting the items_json field in the database.
	FieldItemsJSON = "items_json"
	// FieldResultsTextTemplate holds the string denoting the results_text_template field in the database.
	FieldResultsTextTemplate = "results_text_template"
	// FieldCrewReason holds the string denoting the crew_reason field in the database.
	FieldCrewReason = "crew_reason"
	// FieldPublicNote holds the string denoting the public_note field in the database.
	FieldPublicNote = "public_note"
	// FieldPublishedResultsRevision holds the string denoting the published_results_revision field in the database.
	FieldPublishedResultsRevision = "published_results_revision"
	// FieldCreatedByAccountID holds the string denoting the created_by_account_id field in the database.
	FieldCreatedByAccountID = "created_by_account_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeEvent holds the string denoting the event edge name in mutations.
	EdgeEvent = "event"
	// Table holds the table name of the resultscorrection in the database.
	Table = "results_corrections"
	// EventTable is the table that holds the event relation/edge.
	EventTable = "results_corrections"
	// EventInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventInverseTable = "events"
	// EventColumn is the table column denoting the event relation/edge.
	EventColumn = "event_id"
)

// Columns holds all SQL columns for resultscorrection fields.
var Columns = []string{
	FieldID,
	FieldEventID,
	FieldScope,
	FieldScopeSessionID,
	FieldRevision,
	FieldBasePublicationRevision,
	FieldStatus,
	FieldPublicationOrder,
	FieldItemsJSON,
	FieldResultsTextTemplate,
	FieldCrewReason,
	FieldPublicNote,
	FieldPublishedResultsRevision,
	FieldCreatedByAccountID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/dotwaffle/beamers/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// ScopeSessionIDValidator is a validator for the "scope_session_id" field. It is called by the builders before save.
	ScopeSessionIDValidator func(int) error
	// RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	RevisionValidator func(int) error
	// BasePublicationRevisionValidator is a validator for the "base_publication_revision" field. It is called by the builders before save.
	BasePublicationRevisionValidator func(int) error
	// ItemsJSONValidator is a validator for the "items_json" field. It is called by the builders before save.
	ItemsJSONValidator func(string) error
	// CrewReasonValidator is a validator for the "crew_reason" field. It is called by the builders before save.
	CrewReasonValidator func(string) error
	// PublicNoteValidator is a validator for the "public_note" field. It is called by the builders before save.
	PublicNoteValidator func(string) error
	// PublishedResultsRevisionValidator is a validator for the "published_results_revision" field. It is called by the builders before save.
	PublishedResultsRevisionValidator func(int) error
	// CreatedByAccountIDValidator is a validator for the "created_by_account_id" field. It is called by the builders before save.
	CreatedByAccountIDValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Scope defines the type for the "scope" enum field.
type Scope string

// Scope values.
const (
	ScopePrizegiving Scope = "Prizegiving"
	ScopeStandalone  Scope = "Standalone"
)

func (s Scope) String() string {
	return string(s)
}

// ScopeValidator is a validator for the "scope" field enum values. It is called by the builders before save.
func ScopeValidator(s Scope) error {
	switch s {
	case ScopePrizegiving, ScopeStandalone:
		return nil
	default:
		return fmt.Errorf("resultscorrection: invalid enum value for scope field: %q", s)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusDraft     Status = "Draft"
	StatusReady     Status = "Ready"
	StatusPublished Status = "Published"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDraft, StatusReady, StatusPublished:
		return nil
	default:
		return fmt.Errorf("resultscorrection: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ResultsCorrection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByScopeSessionID orders the results by the scope_session_id field.
func ByScopeSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeSessionID, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByBasePublicationRevision orders the results by the base_publication_revision field.
func ByBasePublicationRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBasePublicationRevision, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByItemsJSON orders the results by the items_json field.
func ByItemsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemsJSON, opts...).ToFunc()
}

// ByCrewReason orders the results by the crew_reason field.
func ByCrewReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCrewReason, opts...).ToFunc()
}

// ByPublicNote orders the results by the public_note field.
func ByPublicNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicNote, opts...).ToFunc()
}

// ByPublishedResultsRevision orders the results by the published_results_revision field.
func ByPublishedResultsRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedResultsRevision, opts...).ToFunc()
}

// ByCreatedByAccountID orders the results by the created_by_account_id field.
func ByCreatedByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByAccountID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByEventField orders the results by event field.
func ByEventField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventStep(), sql.OrderByField(field, opts...))
	}
}
func newEventStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
	)
}
